DETAILS.md
cc/ @bketelsen - ~this is pretty much a copy/paste job from the [gist](https://gist.github.com/arschles/2d5eb22b04e4056cbbe8aa4f58786808) let's work off this from now on~
edit: I simplified this a lot from the above gist. trying to keep the initial scope smaller
=> Adding a "futures" document

API.md
A few mentions slipped through
=> Removing additional mentions of vgoprox

README.md, docker-compose.yml
Fixes https://github.com/gomods/athens/issues/43
=> Adding a docker-compose file

actions/app.go, actions/storage.go, pkg/storage/storage.go
Also:
- Looking for environment variables to choose the proper storage type
- Replacing a `panic` on mongo connection errors with a slightly more informative `log.Fatalf`
Ref https://github.com/gomods/athens/issues/46
=> Splitting out configuration for storage

actions/goget.go, pkg/cdn/cdn.go, pkg/cdn/saver.go
Ref https://github.com/gomods/athens/issues/50
Does not implement one
=> Adding a CDN saver interface

Dockerfile
=> Remove dep ensure from Dockerfile

pkg/cdn/saver.go
I think there is a mistake in Save function signature. If not, just close the PR :)
=> Fix cdn.Saver interface

.travis.yml, actions/app_registry.go, actions/storage.go, pkg/payloads/upload.go, pkg/repo/github/github.go, pkg/repo/repo.go, pkg/storage/backend.go, pkg/storage/backendconnector.go, pkg/storage/fs/all_test.go, pkg/storage/fs/fs.go, pkg/storage/module.go, pkg/storage/mongo/all_test.go, pkg/storage/mongo/getter.go, pkg/storage/mongo/lister.go, pkg/storage/mongo/mongo.go, pkg/storage/mongo/mongo_test.go, pkg/storage/mongo/saver.go, pkg/storage/reader.go, pkg/storage/storage.go, pkg/storage/storageconnector.go, pkg/storage/version.go, pkg/user/mongo/user.go, pkg/user/mongo/user_test.go, pkg/user/user.go
=> fix golint issues

cmd/cli/upload.go
accidentally deleted the branch from #121. This is that branch plus the fixes that were requested
=> changed to using path.Join to build url

.travis.yml, cmd/olympus/actions/app.go, cmd/olympus/actions/eventlog.go, cmd/olympus/actions/events.go, cmd/olympus/actions/feed.go, cmd/olympus/actions/home.go, cmd/olympus/actions/render.go, pkg/storage/minio/lister.go
=> Enpoint for fetching event log

cmd/olympus/actions/actions_test.go, cmd/olympus/actions/app.go, cmd/olympus/actions/eventlog.go, cmd/olympus/actions/events.go, docker-compose.yml, pkg/payloads/upload.go
=> endpoint for cache misses from proxies

cmd/proxy/actions/cache_miss_handler.go, cmd/proxy/actions/fetch.go, cmd/proxy/actions/list.go, cmd/proxy/actions/upload.go, cmd/proxy/actions/version_info.go, cmd/proxy/actions/version_module.go, cmd/proxy/actions/version_zip.go
Set operation name explicitly in handlers to overcome issue with anonymous functions.
=> fix open tracing by setting operation name

.travis.yml, cmd/olympus/actions/actions_test.go, cmd/olympus/actions/app.go, cmd/olympus/actions/eventlog.go, cmd/olympus/actions/events.go, cmd/olympus/actions/package_downloader.go, cmd/olympus/actions/storage.go, cmd/olympus/main.go
Basically just putting bits together in a background job
Fixes: #168
=> Naive implementation of bg job processing downloads

.travis.yml, cmd/olympus/actions/app.go, cmd/olympus/actions/merge_db.go, cmd/olympus/actions/package_downloader.go, cmd/proxy/actions/cache_miss_fetcher.go, cmd/proxy/actions/fetch.go, cmd/proxy/actions/upload.go, pkg/storage/azurecdn/storage.go, pkg/storage/backendconnector.go, pkg/storage/fs/fs_test.go, pkg/storage/fs/lister_test.go, pkg/storage/fs/saver.go, pkg/storage/mem/mem_test.go, pkg/storage/minio/lister_test.go, pkg/storage/minio/minio_test.go, pkg/storage/minio/saver.go, pkg/storage/mongo/lister_test.go, pkg/storage/mongo/mongo_test.go, pkg/storage/mongo/saver.go, pkg/storage/olympus/saver.go, pkg/storage/rdbms/lister_test.go, pkg/storage/rdbms/rdbms_test.go, pkg/storage/rdbms/saver.go, pkg/storage/saver.go
Bonus fix, parallelizing the upload to Azure Blob Storage.
I have no pride, tell me if there's anything I need to change!
=> Add Context to Saver Interface

Makefile
fixes https://github.com/gomods/athens/issues/191
=> spinning up required services in the makefile dev target

cmd/olympus/actions/storage.go, cmd/proxy/actions/storage.go, pkg/storage/fs/all_test.go, pkg/storage/fs/fs.go, pkg/storage/mem/mem.go
`New()` checks for root directory present in fs, returns an error if it does not exist or if any other problem was encountered.
closes #59
=> basic root dir pre check on fs storage.New

cmd/olympus/actions/app.go, cmd/olympus/actions/eventlog.go, cmd/olympus/actions/storage.go, cmd/olympus/models/models.go, cmd/proxy/actions/app.go, cmd/proxy/actions/cache_miss_fetcher.go, cmd/proxy/actions/storage.go, cmd/proxy/models/models.go, pkg/config/env/gcp.go, pkg/config/env/go.go, pkg/config/env/minio.go, pkg/config/env/mongo.go, pkg/config/env/olympus.go, pkg/config/env/redis.go, pkg/config/env/storage.go, pkg/config/module.go, pkg/storage/azurecdn/storage.go, pkg/storage/gcp/all_test.go, pkg/storage/gcp/save_test.go, pkg/storage/gcp/saver.go, pkg/storage/olympus/getter.go, pkg/storage/s3/save_test.go, pkg/storage/s3/storage.go
Moved config and env into a single package to increase readability of env dependencies.
=> Env and config refactor

pkg/module/module.go
When running the CLI's upload command for the first time, I got a panic if the `.gitignore` file did not exist. This is because of the difference between a *nil interface* and a *nil pointer*. This PR fixes it, but I also noticed that we ignore the error for reading a .gignore file, we should potentially check if it's `os.IsNotExist` err and maybe panic otherwise? Happy to update the pr based on the behavior you'd like.
=> Fix upload nil pointer dereference

pkg/config/env/cdn.go, pkg/storage/azurecdn/storage.go, pkg/storage/gcp/saver.go, pkg/storage/s3/storage.go
This should be enough for serving CDN links. 
Connecting CDN to backing storage is always a manual task on storage setup. 
Fixes: #193 
Fixes #195 
Fixes #178
=> Added configurable CDN endpoint

.travis.yml, scripts/get_buffalo.sh
As of this writing, latest is v0.12.3
=> WIP: always downloading a fixed buffalo CLI version

DEVELOPMENT.md, README.md
partially covers https://github.com/gomods/athens/issues/221
=> Refactoring readme and adding a DEVELOPMENT doc

cmd/olympus/actions/app.go, cmd/proxy/actions/app.go, pkg/config/env/csrf.go
This is useful at least for local development
cc/ @marwan-at-work
=> Adding option to disable CSRF protection

.gitattributes
no longer will we get mixed line endings
I think md,toml and yml should be good. go fmt takes care of go files already.
=> normalize all line endings for the repo

.travis.yml, scripts/check_deps.sh
also remove windows line endings on .travis.yml again
=> add check for gopkgs to run dep ensure on changes

.travis.yml
=> i need to slow down

README.md
- added project status badges; build status, test coverage, godoc, GoreportCard
- fixes https://github.com/gomods/athens/issues/259
=> add status badges

pkg/storage/gcp/bucket.go, pkg/storage/gcp/bucket_cloud.go, pkg/storage/gcp/checker.go, pkg/storage/gcp/deleter.go, pkg/storage/gcp/gcp.go, pkg/storage/gcp/gcp_test.go, pkg/storage/gcp/getter.go, pkg/storage/gcp/lister.go, pkg/storage/gcp/saver.go
This will set us up to create the mock for #263
=> abstract gcp bucket into interface

pkg/log/log_test.go
Fixes https://github.com/gomods/athens/issues/279
=> Athens: add log tests to cloud formatters

pkg/storage/deleter.go, pkg/storage/fs/deleter.go, pkg/storage/fs/deleter_test.go
=> storage: return ErrVersionNotFound from fs Deleter

pkg/storage/minio/all_test.go, pkg/storage/minio/deleter.go, pkg/storage/minio/deleter_test.go
=> storage: return ErrVersionNotFound from minio Deleter

pkg/storage/mongo/deleter.go, pkg/storage/mongo/deleter_test.go
=> storage: return ErrVersionNotFound from mongo Deleter

Makefile
We were only building the proxy
=> Adding registry build to the makefile

cmd/proxy/actions/app.go, cmd/proxy/actions/app_proxy.go, pkg/download/doc.go, pkg/download/download.go, pkg/download/get_module_versions.go, pkg/download/latest.go, pkg/download/list.go, pkg/download/version_info.go, pkg/download/version_module.go, pkg/download/version_zip.go, pkg/module/go_get_fetcher.go, pkg/storage/getter_saver.go
=> download: clean up Kahona

pkg/download/download.go, pkg/download/get_module_versions.go, pkg/download/version_info.go, pkg/download/version_module.go, pkg/download/version_zip.go
fixes https://github.com/gomods/athens/issues/358 and random handler bugs
=> download: fix handler errors

pkg/module/disk_ref.go, pkg/paths/decode.go, pkg/paths/encode.go, pkg/paths/encode_decode_test.go, pkg/paths/path.go
fixes https://github.com/gomods/athens/issues/356
=> athens: encode/decode modules per cmd/go rules

pkg/module/disk_ref.go, pkg/module/disk_ref_test.go, pkg/module/fetch.go, pkg/module/go_get_fetcher.go, pkg/module/go_get_fetcher_test.go, pkg/module/noop_ref.go, pkg/module/ref.go
=> zip.Close() also clears the GOPATH of the underlying diskRef

pkg/download/download.go, pkg/module/go_get_fetcher.go
This got lost in the shuffle while rebasing commits from our last session.
=> Proxy: fill cache on Protocol.Version

DEVELOPMENT.md, Makefile
Fixes dev part of https://github.com/gomods/athens/issues/262
=> Makefile: minimum dependencies for dev environment

pkg/download/goget/goget.go
After doing some digging, turns out cmd/go sends all errors to stderr, and all expected output to stdout. So we don't need the ugly hack from before anymore.
=> Download: separate stdout from stdin when running cmd/go

LICENSE
to refer to the athens authors. this addresses but doesn't completely close out https://github.com/gomods/athens/issues/1
cc/ @leighmcculloch
(P.S. I used the GH UI to create this patch, and it didn't let me create my branch on my fork. I'm not doing the right thing and I'm sorry to everyone - I used the web editor/branch/PR tool out of pure laziness, so I have no excuse and I'm sorry :100: times!)
=> Updating the license author

pkg/log/entry.go
Removed TODO comment as it is solved by https://github.com/gomods/athens/pull/320
=> pkg/log: we do have our Error struct now

Gopkg.lock, Gopkg.toml, vendor/github.com/bketelsen/buffet/opentracing.go
This change is required to start using buffet for tracing with a normal context
=> Update buffet to the tip of the master in athens

pkg/module/go_get_fetcher.go, scripts/get_dev_tools.sh, scripts/test_e2e.sh
=> Download: move cache location

CONTRIBUTING.md
So that folks new to Go can sign up for the slack easily
=> Changing gophers slack link to be the invite link

pkg/storage/azurecdn/blob_store_client.go, pkg/storage/azurecdn/storage.go, pkg/storage/fs/fs.go, pkg/storage/fs/lister.go, pkg/storage/fs/saver.go, pkg/storage/mem/mem.go, pkg/storage/minio/lister.go, pkg/storage/minio/minio.go, pkg/storage/minio/saver.go, pkg/storage/module/delete.go, pkg/storage/module/delete_test.go, pkg/storage/module/upload.go, pkg/storage/module/upload_test.go, pkg/storage/s3/storage.go
last pr and I think we're all set with having error operations in all of the code that is being used today :)
=> pkg/storage: add err ops

pkg/module/download.go, pkg/module/go_get_fetcher_test.go, pkg/module/module.go
Add errors.Op to missing things in pkg/module
=> pkg/module: add errors op

docs/config.toml, docs/content/faq.md, docs/themes/hugo-theme-learn/layouts/partials/menu.html
See https://www.reddit.com/r/golang/comments/9704se/the_missing_package_registry_for_golang/?utm_source=share&utm_medium=mweb&_branch_match_id=557725032397199929 for the source material
Preview available at: https://deploy-preview-478--gomods-athens.netlify.com/faq/
=> Convert Aaron's reddit post into a FAQ

pkg/module/filter.go, pkg/module/filter_test.go, scripts/get_buffalo.sh
ShouldProcess of a filter cannot determine the behavior of the caller with additional `Private` state implemented in #456 
This way we force the caller to decide
Fixes: #472
=> Removed ShouldProcess

pkg/module/filter.go
+ moved op inside the function
=> pkg/module: fix comment

pkg/log/buffalo_formatter.go
Buffalo can give you nil data sometimes, if it does, then just log the message.
=> pkg/log: log msg if no data given

docs/content/_index.md
This PR adds basic steps for trying out Athens using the happy-path repo and in memory storage
Co-authored-by: Carolyn Van Slyck <carolyn.vanslyck@microsoft.com>
=> Update the doc site index to include try it out langauge

cmd/proxy/actions/app.go, cmd/proxy/actions/app_proxy.go, cmd/proxy/actions/cache_miss_fetcher.go
=> Proxy: remove unused arguments

pkg/eventlog/fs/pointer_registry.go
=> refactor SetPointer return base on golint suggestion

cmd/olympus/actions/app.go, cmd/proxy/actions/app_proxy.go, pkg/config/env/go.go, pkg/download/download.go, pkg/download/download_test.go
Fixes https://github.com/gomods/athens/issues/523
=> pkg/download: use worker pool to limit concurrent gogets

docs/content/_index.md, docs/content/walkthrough.md
Preview available at https://deploy-preview-505--gomods-athens.netlify.com/walkthrough/
=> Walkthrough how the proxy works

Makefile
=> Remove separate docker volume prune command

.gitignore
The worst https://en.wikipedia.org/wiki/.DS_Store
=> Athens: add .DS_Store to gitignore

pkg/storage/azurecdn/storage.go, pkg/storage/fs/checker.go, pkg/storage/fs/deleter.go, pkg/storage/fs/lister.go, pkg/storage/fs/saver.go, pkg/storage/gcp/deleter.go, pkg/storage/gcp/getter.go, pkg/storage/gcp/lister.go, pkg/storage/gcp/saver.go, pkg/storage/minio/checker.go, pkg/storage/minio/deleter.go, pkg/storage/minio/getter.go, pkg/storage/minio/lister.go, pkg/storage/mongo/checker.go, pkg/storage/mongo/deleter.go, pkg/storage/mongo/getter.go, pkg/storage/mongo/lister.go, pkg/storage/mongo/saver.go, pkg/storage/s3/storage.go, pkg/storage/storage_tests/module_storage/storage_test.go
Making behavior consistent on top of that
=> KindNotFound for all storages

README.md
* fix some typos
* make the markdown links in the "Coding Guidlines" render correctly
* remove stray newlines between project status badges
=> README.md: various fixes

charts/proxy/templates/deployment.yaml, scripts/test_unit.sh
The env var wasn't renamed in few places.
=> fix mongo env var name

config.example.toml, go.mod, go.sum
Won't need to do this once the PR that removes Gopkg.* is in.
=> update go.mod file

scripts/test_e2e.sh
=> Fix end 2 end test

CONTRIBUTING.md
=> Add how to claim an issue

pkg/module/disk_ref.go
=> Fix module.ClearFiles operation name

pkg/download/protocol.go, pkg/module/go_get_fetcher.go, pkg/stash/stasher.go, pkg/stash/with_pool.go, pkg/stash/with_pool_test.go, pkg/stash/with_singleflight.go, pkg/stash/with_singleflight_test.go
Fixes https://github.com/gomods/athens/issues/526
=> Trace stash operations

docs/content/walkthrough.md
Make set up simpler by relying on the default value in that flag :)
=> Remove config flag from walkthrough doc

pkg/download/protocol.go
As far as my understanding this is a typo, please correct me if I'm wrong :thinking:
=> Fix typo in comment

docs/content/_index.md, docs/content/try-out.md
Make the homepage clearer #741 .
Created a new file try-out.md and moved Try Out section from the homepage to that file.
Fixes #741
=> Docs move try-out from homepage to a new page

config.dev.toml
I had a lot of red line endings at the end of the line while going through my editor, which does not give a pleasant reading experience
I am removing the extra unnecessary white space.
=> Remove unnecessary white space form config file

README.md, docs/content/contributing/new/github.md
Adding more resources to newcomers #752 .
Fixes #752
=> Docs: Added "makeapullrequest.com" links

pkg/storage/mongo/mongo.go
=> Allow users to use certificates from the system cert pool

docs/content/contributing/_index.md, docs/content/design/_index.md, docs/content/install/_index.md, docs/content/intro/_index.md, docs/themes/hugo-theme-learn/layouts/install/list.html
Section headers in the docs were empty and that made it confusing how to navigate the docs.
I added content to the headers of each section.
Fixes #733
=> Adding section headers to the docs

docs/content/faq.md
The docs did mention that we have support for GCP and datadog for tracing.
Update the docs to mention the same
Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.
=> Update docs to mention that we have added gcp and stackdriver as well

pkg/storage/fs/saver.go
When creating files, don't set the permission bits as 0777 (os.ModePerm), since that will cause them to be marked as executable. Instead set them to 0666.
Add a comment explaining the umask will be subtracted, which is why 0666 (and not e.g. 0644 or 0600) is appropriate.
Fixes #781
=> storage/fs: don't mark files as executables

scripts/ps/test_unit.ps1
Added env vars for mino and mogo.
Fixes #798
=> Updated test_unit.ps1 according to test_unit.sh

cmd/proxy/actions/app.go, config.dev.toml, pkg/config/config.go, pkg/config/config_test.go
Updates https://github.com/gomods/athens/issues/813
=> Remove CSRF option from config

init.ps1
Removing unnecessary redis initializtion in powershell script. We did same for makefile #785 
Removed redis initialization from init.ps1 file
**Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.**
Fixes #817
=> Remove redis initialization from init.ps1 file

pkg/storage/s3/s3_test.go
Canceling all created context with timeouts
Code edit
**Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.**
Fixes #824
=> Cancel context with timeouts

.github/ISSUE_TEMPLATE/bug_report.md, .github/PULL_REQUEST_TEMPLATE.md
small grammar check
No backing issue
=> Small corrections of the templates

docs/content/_index.md, docs/content/configuration/authentication.md, docs/content/design/_index.md, docs/content/design/communication.md, docs/content/design/proxy.md, docs/content/faq.md, docs/content/install/install-on-kubernetes.md, docs/content/install/shared-team-instance.md, docs/content/try-out.md, docs/content/walkthrough.md
After we agreed on the naming docs needs to be updated
Updated all occurences of `the proxy` with `the Athens proxy`
**Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.**
No backing issue
=> Replace all occurrences of proxy with official name

docs/content/_index.md, docs/content/intro/why.md
Fixes https://github.com/gomods/athens/issues/749
Dependent on this PR: https://github.com/gomods/athens/pull/864
=> doc: why does it matter

.travis.yml, cmd/proxy/Dockerfile
The CI build on master is broken.
* Do not use an invalid version (with a whitespace) in the default VERSION value in our dockerfile.
* Do a docker build on PR builds so that we find problems before we merge.
Addresses broken build https://travis-ci.org/gomods/athens/builds/453641688#L1457
=> Fix CI build

scripts/push-docker-images.sh
I missed a few (very important steps) that were setting the image name in my last PR #909! 😊
=> Fix remaining docker image names

docs/content/configuration/authentication.md, docs/content/install/shared-team-instance.md, docs/content/walkthrough.md
Some more typos spotted while reading the docs :)
- to _ all the way
Fixes #
=> Fixed more typos

DEVELOPMENT.md
Running Hugo using the method in the docs didn't work, so I fixed the docs up.
+ Mention `make docs` definition
+ Fix docker run command
~ Change docker command to run it from project root
I don't think there's a related issue
=> Improve docs for developing docs

charts/proxy/templates/deployment.yaml, cmd/proxy/actions/app_proxy.go, cmd/proxy/actions/readiness.go
Adding `/readiness` endpoint for readinessProbe 
readiness endpoint created, charts template updated to include readiness and liveness probes
Fixes #891
=> Readiness probe

docs/content/walkthrough.md
The walktrough docs part about running proxy were not accurate/up-to-date  
Updated the bash/ps scripts
No issue
=> update walkthrough docs

docs/content/configuration/storage.md
Support for Alibaba OSS can be provided by Minio. So lets mention it in the docs.
I also checked that the support works by running Athens against OSS.
Update docs with how to configure Alibaba OSS.
Fixes #775
=> Alibaba OSS Storage

pkg/download/protocol.go
List endpoint is slower, this is one possible optimization
Add a waitgroup to run the two things in parallel.
Fixes #990
=> 1st attempt at speeding up list endpoint

README.md
Removing a duplicate word "used" from the README.md file.
=> Remove duplicate word from README.md

scripts/ps/test_e2e.ps1, scripts/test_e2e.sh
5 seconds sleep time is too much! Let us reduce it. While not scientific, saves ~1min on our test suite on the optimistic side.
Sleep is reduced to 0.5.
Fixes #
=> reduce sleep time in e2e between http calls

cmd/proxy/actions/app.go, cmd/proxy/actions/auth.go
=> Remove unused session auth

config.dev.toml
After PR change env var for port .
the example config toml file should changed too
=> fix toml note

cmd/proxy/actions/app_proxy.go, pkg/download/handler.go, pkg/storage/handler.go
The catalog handler should not go through download protocol.
Move to its own handler for storage backend.
=> Move catalog handler out of download protocol

config.dev.toml
Fix `overide` to be `override`
=> config.toml: fix override typo

config.dev.toml, pkg/config/config.go, pkg/config/config_test.go
We should keep code defaults and config.toml defaults the same.
I've added a test so that we know if they're out of sync.
=> Check code defaults and config.toml defaults are the same

README.md
a typographical error in README.md
=> README.md: fix typographical error

charts/athens-proxy/templates/_helpers.tpl, charts/athens-proxy/values.yaml, docs/content/install/_index.md, docs/content/install/install-on-aci.md, docs/content/install/shared-team-instance.md
Nothing really, I'm just updating docs 😄 
I updated docs 😄 
This is a follow-up to https://github.com/gomods/athens/releases/tag/v0.3.0
cc/ @marwan-at-work b/c you cut the v0.3.0 release and we talked about this on Slack. Thanks @marwan-at-work 💯 !
=> Updating docs to reference v0.3.0

.drone.yml
Added the ability to test our Redis Stasher Implementation on PRs
=> drone: add redis lock test

pkg/paths/path.go
=> pkg/paths: fix typos in err message and doc.

.github/ISSUE_TEMPLATE/bug_report.md
We do not use Buffalo anymore so we shouldn't ask about it in our bug tmpl
Removed the question
=> rm buffalo question

Makefile, init.ps1, scripts/ps/get_dev_tools.ps1, scripts/ps/test_e2e.ps1
> Remove references to Buffalo since it is no longer used in Athens.
> Searched the repository for all references to "buffalo" and removed them.
Fixes #1149
=> #1149 Remove references to Buffalo

charts/athens-proxy/Chart.yaml, charts/athens-proxy/README.md, charts/athens-proxy/templates/config-ssh-git-servers.yaml, charts/athens-proxy/templates/deployment.yaml, charts/athens-proxy/templates/secret-ssh-git-servers.yaml, charts/athens-proxy/values.yaml
=> [chart] add support to configure ssh-secured git servers

.drone.yml, test/ct.yaml
=> add chart linting step to drone pipeline

.circleci/config.yml
I think this will help @rimusz in https://github.com/gomods/athens/pull/1225/files
=> Adding basic circleci config

pkg/storage/compliance/tests.go, pkg/storage/s3/checker.go
Fixes https://github.com/gomods/athens/issues/1219
=> storage/s3: fix checker prefix

docs/content/design/from-vcs2user.md
Type-o in docs.
Fixed the type-o :D
N/a
=> FIXED type-o in docs

DEVELOPMENT.md
Typo in the DEVELOPMENT.md doc
`.See below for insrtuctions to do both!`
changed to `See below for instructions to do both!`
n/a
=> fixed typos

pkg/storage/gcp/checker.go
What is the problem I am trying to address?
Currently our storage.Exists implementation checks only for the mod file. This can be problematic if i.e. zip or info uploads failed.
How is the fix applied?
I'm checking if the len of objects equals 3 (zip, mod, info)
=> GCS: Use no. of objects for Exists check

pkg/download/version_module.go
This aligns `ModuleHandler` with `ZipHandler` and `InfoHandler` logic.
As described in #1285, when setting up `redirect` or `async_redirect` DownloadMode, modules that currently do not exist in the storage cause `go get` complain `301 response missing Location header`.
Reason seems to be that the `<module>/@v/<version>.mod` endpoint does not return the `Location` header while both `<module>/@v/<version>.zip` and `<module>/@v/<version>.info` return valid `Location` header.
Comparing logic of the handlers for endpoints above, the error checks in `ModuleHandler` seem to be swapped around. This PR fixes that.
Fixes #1285
=> Fixing error check logic for module downloads in case of redirects.

pkg/download/handler_test.go
There was a bug in the redirects for the `.mod` endpoint only. Our redirect tests only tested for the `.info` endpoint which is why it wasn't caught. I added redirect tests for all `.mod`, `.info` and `.zip` endpoints. 
Related to https://github.com/gomods/athens/issues/1285
=> download: expand redirect tests

cmd/proxy/actions/app_proxy.go, config.dev.toml, pkg/config/config.go, pkg/config/config_test.go, pkg/download/protocol_test.go, pkg/download/upstream_lister.go, pkg/module/all_test.go, pkg/module/go_get_fetcher.go, pkg/module/go_get_fetcher_test.go
support fetch from goproxy instead of from the original repo
provide a config/env for GOPROXY to Go mod/list Command
Fixes #1294
=> support fetch from goproxy

config.dev.toml, pkg/config/s3.go, pkg/storage/s3/s3.go
Adding endpoint credentials to AWS Storage layer
I have created a credentialsProvider chain, which looks for credentials in the endpoint. If the endpoint is present and returns the right response, we will use it to retrieve credentials, otherwise use static credentials, and at the credentials from the env if they are present.
Fixes #1283
=> endpoint creds

cmd/proxy/actions/app_proxy.go, pkg/download/protocol.go, pkg/download/protocol_test.go, pkg/module/go_get_fetcher.go, pkg/module/go_vcs_lister.go, pkg/module/prepare_env.go, pkg/module/upstream_lister.go, pkg/module/zip_read_closer.go
it's a refactor about upstream lister which should in module package.
cc @arschles
=> ref: upstream lister and it's impl to module pkg

docs/content/install/install-on-kubernetes.md
I think I found what seems to be a typo. I believe the intention there was to convey that the default values are being applied but instead the values part was omitted.  
changed the word :)
EDIT: also I'm sorry I didn't open a ticket first but seemed so small and trivial..
=> typo found

go.mod, go.sum, pkg/storage/compliance/tests.go, pkg/storage/fs/lister.go, pkg/storage/minio/lister.go
check semver and go.mod existence to verify a module version
Fixes #1311
=> storage/fs,minio: fix list module with same prefix

docs/content/faq.md
Close #1137
Add list of supported VSC servers in FAQ.
Created a new section in FAQ that lists supported VCSs.
Fixes #1137
=> docs: Add list of supported VCS servers

docs/content/configuration/upstream.md
Just a couple quick markdown fixes while reading through the upstream documentation
=> Fix try-out link

docs/content/install/install-on-kubernetes.md
A tiny mistake in the docs.
I gathered my limited powers of concentration and typed three words 😉
No issue created, as I felt it would be an unnecessary bureaucracy.
=> Fix kubernetes installation docs

.drone.yml, pkg/stash/with_azureblob_test.go
Enable Azure storage and stasher tests in drone
=> Enable Azure storage and stasher tests in drone

docs/content/configuration/download.md
The [download mode](https://docs.gomods.io/configuration/download/) docs didn't say how to point Athens to the HCL file
I added instructions on how to point Athens to the HCL file
N/A
=> Updating the download config docs

DEVELOPMENT.md
Fixes minor typo in DEVELOPMENT.md
=> Remove extraneous period in DEVELOPMENT.md

CONTRIBUTING.md
`CONTRIBUTING.md` didn't have a header
I added a header
N/A
=> Adding a header to the contributing doc

cmd/proxy/actions/app.go, go.mod, go.sum, pkg/log/format.go, pkg/middleware/log_entry.go, pkg/middleware/log_entry_test.go, pkg/middleware/request.go
Fixes https://github.com/gomods/athens/issues/1521
Also adds a new dev formatter so things look prettier than Logrus'es TextFormatter...I'm tempted to make it even more fancy but for now it works.
=> always use request logging middleware

charts/athens-proxy/Chart.yaml, charts/athens-proxy/templates/deployment.yaml, config.dev.toml, docs/content/configuration/storage.md, pkg/config/config_test.go, pkg/config/s3.go, pkg/storage/s3/doc.go, pkg/storage/s3/s3.go, pkg/storage/s3/s3_test.go
Right now you cant use path style url with s3 storage
Add ForcePathStyle to S3Config
=> Add forcepathstyle config for s3

docs/themes/hugo-theme-learn/layouts/partials/menu-footer.html
We have to pay for the Netlify service powering docs.gomods.io
I am going to apply for the [open source plan](https://www.netlify.com/legal/open-source-policy/), and it requires that we add a powered by link on the page. This PR adds it
Fixes #
=> Adding "Powered by Netlify" text

docs/content/install/install-on-google-cloud-run.md
Documentation out of date
Fixes #1571
=> update version info in google-cloud-run docs

cmd/proxy/actions/app_proxy.go, pkg/stash/stasher.go, pkg/stash/with_azureblob_test.go, pkg/stash/with_etcd_test.go, pkg/stash/with_redis_sentinel_test.go, pkg/stash/with_redis_test.go, pkg/storage/backend.go, pkg/storage/checker.go, pkg/storage/compliance/benchmarks.go, pkg/storage/compliance/tests.go
Prerequisite to External Storage
Fixes #1578
=> pkg/storage: make Checker optional in storage.Backend

.github/PULL_REQUEST_TEMPLATE.md
The section for how to write `Fixes #` was unclear. Specifically, when I wrote "issue", that might not have been very clear to people not as familiar with GitHub.
I added clarity to the commented above the "What GitHub issue(s) does this PR fix or close?" section
=> Sample pr template change

cmd/proxy/actions/app_proxy.go, cmd/proxy/actions/sumdb.go, cmd/proxy/actions/sumdb_test.go
The function to create the new checksum DB proxy was called
`sumdbPoxy`. It should be called `sumdbProxy`
I've renamed the function and its usage everywhere.
None
=> "sumdbPoxy" ==> "sumdbProxy"

Makefile, docker-compose.yml, go.mod
Bring go version in consistency across configs
go version requirement in `go.mod`, `Makefile`, `docker-compose` match with Dockerfile
=> update go version in configs

DEVELOPMENT.md
The [release notes](https://github.com/gomods/athens/blob/master/DEVELOPMENT.md#for-people-doing-a-release) are incomplete because they don't include specific instructions for patch releases.
I added instructions that differentiate between patch and minor releases.
Fixes https://github.com/gomods/athens/issues/1596
=> Updating the release notes

charts/athens-proxy/Chart.yaml, charts/athens-proxy/values.yaml
We did a v0.9.0 release and the Helm chart versions are now out of date
I updated them 😄 
None
=> Updating chart and docker image versions for 0.9.0

docs/content/configuration/prefill-disk-cache.md
=> fix typo in docs

go.mod, go.sum
My attempt at trying to fix #1632.
N/A
Fixes #1632
=> Upgrade AWS SDK to v1.32.7

README.md
There is office hours text on the README, but we don't do office hours anymore..
I've removed it from the README
=> Removing office hours text from the README

appveyor.yml, cmd/proxy/actions/app_proxy.go, cmd/proxy/actions/index.go, cmd/proxy/actions/storage.go, config.dev.toml, go.mod, go.sum, pkg/config/config.go, pkg/config/config_test.go, pkg/config/index.go, pkg/config/mysql.go, pkg/config/postgres.go, pkg/config/storage.go, pkg/download/protocol_test.go, pkg/index/compliance/compliance.go, pkg/index/indexer.go, pkg/index/mem/mem.go, pkg/index/mem/mem_test.go, pkg/index/mysql/mysql.go, pkg/index/mysql/mysql_test.go, pkg/index/nop/nop.go, pkg/index/postgres/postgres.go, pkg/index/postgres/postgres_test.go, pkg/stash/stasher.go, pkg/stash/stasher_test.go
This is the first of possibly a couple of more PRs to try and integrate pkg.go.dev (pkgsite) with Athens. 
Pkgsite uses https://index.golang.org to discover new module versions so that they are searchable and are parsed ahead of time. More on pkgsite's design [here](https://github.com/golang/pkgsite/blob/master/doc/design.md). 
This PR adds a `/index` endpoint that tries to adhere to the same logic and format in `index.golang.org/index`
To support a /index endpoint we create a new Indexer interface: 
```
type Indexer interface {
Index(ctx context.Context, mod, ver string) error
Lines(ctx context.Context, since time.Time, limit int) ([]*Line, error)
}
```
This is different (and separate) from a storage.Backend for one important reason: 
- A storage backend might not store modules in a …
=> implement /index endpoint

docs/content/configuration/download.md, docs/content/configuration/storage.md, docs/content/contributing/new/docs.md, docs/content/install/using-docker.md
Correct 404 issues within documentation
Replaced broken links with new paths.
Fixes #1643
=> Fix 404s within documentation

.drone.yml
Athens now uses go1.17 which is latest. Update drone ci to do the
same for better indication of our CI results.
Update droneci yaml definition.
N/A
Fixes #
=> Update droneci to use go1.17

docs/content/install/install-on-google-cloud-run.md
see https://github.com/gomods/athens/issues/1571#issuecomment-599221107
The google cloud commands have changed, as has the version numbers.
This was already predicted in a comment on an older, closed issue, so I just followed those steps.
=> Update Cloud Run version and docker steps per #1571

.github/dependabot.yml
I am trying to update dependencies automatically using dependabot. This will help us remove update dependencies automatically.
Fixes #
=> Add dependabot for automatic dependency update

.circleci/config.yml
CircleCI rolled out deprecation for ubuntu 14.04.
Moving to the latest release.
Following: https://circleci.com/docs/2.0/images/linux-vm/14.04-to-20.04-migration/?mkt_tok=NDg1LVpNSC02MjYAAAGCndcffOyWWCJwowDNN0tya6mbisfhi1qTk475NC30ZHs9SYkb-KALw97fCv1sxMKyJKls6VKCNC5JsEp_XKET_Ug3Ul71_aLsiquy7by_OhEX#changes
Fixes #
=> Switch to latest supported CircleCI Ubuntu image

charts/athens-proxy/Chart.yaml, cmd/proxy/actions/app_proxy.go, config.dev.toml, pkg/config/config.go, pkg/config/config_test.go
Addressing a TODO to remove GOPROXY.
Follow up from
https://github.com/gomods/athens/pull/1564
Deleted GOPROXY code.
Fixes #
=> Remove deprecated GOPROXY in favor of GoBinaryEnvVars

pkg/storage/s3/checker.go
This is an alternative implementation of #1840, with goroutines.
@manugupt1 @ngshiheng @r-ashish
=> Calling HeadObjectWithContext() concurrently to check the existence of a module

.github/workflows/ci.yml
Fixes the CI build for pull requests and pushes to main
=> chore: fix ci build

go.mod, go.sum
Logrus 1.9.3 has a fix for a vulnerability: https://github.com/sirupsen/logrus/releases/tag/v1.9.3.
Upgrade the dependency
N/A
=> Upgrade logrus from 1.7.0 => 1.9.3

pkg/log/entry.go
When outputting JSON logs, there are no additional fields.
Output that fields
Fixes #
=> should use errors.AsErr to extract and detect errors.Error

cmd/proxy/Dockerfile
ARCH is wrong in the second case
https://github.com/gomods/athens/pull/2002#discussion_r1839776540
Setting the value back to x86_64
Fixes #2002
=> fix arch selection for github-app helper

cmd/proxy/actions/home.go, docs/content/configuration/home-template.md
=> Add utf8 charset meta to the proxy home

pkg/storage/s3/lister.go
By default `ListObjectsV2()` returns the first 1000 objects matching the list parameters.
Normally this is fine, as it supports up to 333 versions (1000 / 3 files in proxy-triplet). For modules with more versions, this is insufficient and must be upgraded to paginate.
Athens `/list` endpoint returning a partial response when used with the s3
backer and many (>333) versions.
Using the paginator provided with the s3-v2 API for list queries.
N/A (I haven't made or seen one).
=> Add pagination to s3 lister

.github/workflows/ci.yml, .golangci.yml, pkg/config/config.go, pkg/index/mem/mem.go, pkg/middleware/filter.go, pkg/middleware/validation.go, pkg/storage/checker.go, pkg/storage/gcp/saver.go
This updates golangci-lint to v2
=> chore: bump golangci-lint to v2

.goreleaser.yml
This updates the GoReleaser config, which is not out of date.
Updated the GoReleaser config and verified using `goreleaser check`.
=> chore: update goreleaser config

cmd/proxy/Dockerfile
Missing `tzdata` in the docker image, solves #1976
Add `tzdata`
Fixes #1976
=> fix: add tzdata to image
