gomods/athens

- Dockerfile
I don't recall if buffalo:development is the image to use for developing buffalo apps, or if it's a tracking tag for the dev branch in buffalo.
Anyway, if the `v0.11.0` tag can be used for developing buffalo, we should definitely use it because it's immutable
> Update the buffalo version in dockerfile

- pkg/storage/lister.go
- pkg/storage/memory/lister.go
I used this function for early debugging of the memory storage driver. Now that I’m writing tests for it (see
https://github.com/gomods/athens/pull/21), it is no longer valuable to have it. Also, as the proxy is used in the real world, it’s no longer going to be scalable to use this function.
> Removing the All() function from storage listers

- actions/app.go
- actions/cdn.go
- actions/goget.go
- pkg/cdn/fake/getter.go
- pkg/cdn/getter.go
- templates/goget.html
This PR:
- Creates a fake CDN Getter implementation
- For use in tests and stubs
- Passes the CDN getter along into the GoGet middleware
- Using the fake CDN Getter implementation for now
- Uses the getter to determine whether a `baseURL/module` is available in the CDN
- Moves the `<meta ...>` tag into a template and renders the template
Fixes https://github.com/gomods/athens/issues/44
Also note that #44 prescribes that we make the middleware configurable, but the CDN getter effectively does that for us, since we can store any base URL in the registry DB. That will allow us to support as many domains as we like (gomods.io, gopackages.io, myradmoduledb.io, ...)
> Using the CDN getter in the GoGet middleware

- actions/app.go
- actions/app_proxy.go
- actions/app_registry.go
This patch logically splits the registry and proxy actions apart, and forces you to configure Athens as a proxy or a registry, but not both.
Fixes https://github.com/gomods/athens/issues/46
> Splitting actions into registry and proxy

- webpack.config.js
Buffalo tries to find `manifest.json` in assetBox path:
```
// github.com/gobuffalo/buffalo/render/template.assetPath
manifest, err := s.AssetsBox.MustString("manifest.json")
// actions/render.go
var assetsBox = packr.NewBox("../public")
```
> Fix assets manifest path

- .travis.yml
The conflicts were checked in at https://github.com/gomods/athens/commit/cccaaab741b7da4edb71066e9b59ae9cf1ee9d91.
Instead of pushing a revert commit directly to master, I've done this instead 😄
> Fixing conflicts in the travis yaml file

- README.md
Added instructions for setting up required environment variables under bash-like and fish shells.
Added instructions to create and initialize the application database.
Also there were line endings inconsistent with the rest of the code base so I removed them.
closes #139
> Env readme

- cmd/olympus/grifts/eventlog_sync.go
This is the first patch in a series that implements https://github.com/gomods/athens/issues/107. I am keeping PRs as small as possible
> Adding an empty grift for doing pull synchronization for event logs

- pkg/eventlog/mongo/pointer_registry.go
- pkg/eventlog/mongo/pointer_registry_test.go
use correct order for testify require.Equal
also make an error check more compact like the rest of the code base
> tidy up pointer registry mongo driver

- cmd/proxy/actions/storage.go
- pkg/storage/fs/all_test.go
- pkg/storage/mem/mem.go
- pkg/storage/mem/mem_test.go
Fixes #165 
* adds separate mem pkg which uses the fs implementation under the hood
It's possible to call NewStorage() multiple time and get the same storage instance which makes the behavior consistent with other storage drivers
> Separate in-mem storage and test

- .travis.yml
Two things are missing for codecov to work :
* Add the repository to codecov.io: https://codecov.io/gh/gomods/athens
* Change the CODE_COV env var inside travis.yml to 1
Fixes (partially) #120
> Codecov & travis.yml cleanup

- Makefile
This makes it easier to get started. You can type `make dev` on the cmdline and it executes the right docker-compose command to get all dependency services up
> adding a "dev" target to the makefile

- pkg/storage/olympus/getter.go
This makes sure we don't persist in the Zeus storage whatever Olympus gives us.
> Zeus: check for status code in ModuleStore.Get

- cmd/olympus/actions/app.go
- cmd/proxy/actions/cache_miss_reporter.go
- pkg/config/env/olympus.go
So that Zeus can happily run at 3000.
> Olympus: default port to 3001

- PROXY.md
- REGISTRY.md
Todo after merging this:
- Redirect the [wiki](https://github.com/gomods/athens/wiki/Proxies-(Zeus)) [pages](https://github.com/gomods/athens/wiki/The-Central-Package-Registry-(Olympus)) to the new proxy.md and registry.md pages
Partially addresses #221
> Moving design docs from the wiki

- cmd/proxy/actions/app.go
- cmd/proxy/actions/cache_miss_fetcher.go
- cmd/proxy/actions/cache_miss_reporter.go
The `gowork/work` package already handles retries, so having our own retries on top of those could be potentially conflicting or unnecessary at best
> Athens: delegate worker retries to gocraft/work

- PHILOSOPHY.md
- README.md
I'm attempting here to document generally how we like to work and set some standards so that newcomers know what to expect when they join our community.
> Adding an athens philosophy document

- Makefile
CLI was removed and so should be the dangling reference within `Makefile`.
> make: drop cli reference

- cmd/olympus/actions/app.go
- cmd/proxy/actions/app.go
- cmd/proxy/actions/app_proxy.go
- cmd/proxy/actions/cache_miss_handler.go
- pkg/config/env/cloud_runtime.go
- pkg/config/env/log.go
- pkg/log/buffalo.go
- pkg/log/buffalo_formatter.go
- pkg/log/buffalo_logger.go
- pkg/log/entry.go
- pkg/log/format.go
- pkg/log/log.go
This PR does two things: 
1. Creates a formatter for buffalo's logs, just so that we can follow the flow of handlers more clearly when developing/debugging only.
2. Creates our own `log` package which will be the broad logging mechanism for the whole Athens system. This PR just defines the behavior of logging so that it can be discussed/tweaked if necessary before changing all the logs in the code base. 
Once this PR is resolved, further prs should come in to spit logs through this package instead of the standard library
Fixes https://github.com/gomods/athens/issues/156
> Athens: introduce log package

- cmd/proxy/actions/app.go
- cmd/proxy/actions/home.go
The home '/' route handler for the proxy app is assigned to `proxyHomeHandler` in (./cmd/proxy/app_proxy.go) line 11.
However on line 112 of (./cmd/proxy/app.go) it is reassigned to the `homeHandler`. Since we can't have two handlers I removed the one from `app.go` for using `homeHandler`.
I am wondering which handler is preferred however, as the 'homeHandler' also includes a new tracing child span and a sleep for one millisecond. If whichever of the two is not needed I will remove that as well.
> Zeus: remove duplicate '/' handler assignment

- cmd/proxy/actions/app.go
- cmd/proxy/actions/auth.go
- cmd/proxy/actions/render.go
For some reason, having two inits in the same package caused panics because the `proxy` variable was being passed down to the Download Protocol Handlers as nil.
> Proxy: fix init nil dereference

- pkg/storage/rdbms/deleter.go
- pkg/storage/rdbms/deleter_test.go
This also fixes a bug caused by calling conn.Destroy on a non-pointer value.
Part of #244.
> storage: return ErrVersionNotFound from rdbms Deleter

- pkg/storage/azurecdn/blob_store_client.go
- pkg/storage/azurecdn/storage.go
Fixes #292
To make the cdn/blob storage implementations consistent (ref: #254 and #280) and enable unit tests. Also goes hand in hand with #264
> extract client for azure strg impl

- cmd/olympus/actions/merge_db.go
- cmd/proxy/actions/cache_miss_fetcher.go
- pkg/eventlog/multireader.go
- pkg/eventlog/multireader_test.go
- pkg/storage/backendconnector.go
- pkg/storage/checker.go
- pkg/storage/deleter.go
- pkg/storage/fs/checker.go
- pkg/storage/fs/deleter.go
- pkg/storage/gcp/checker.go
- pkg/storage/gcp/deleter.go
- pkg/storage/gcp/gcp_test.go
- pkg/storage/gcp/getter.go
- pkg/storage/gcp/saver.go
- pkg/storage/minio/checker.go
- pkg/storage/minio/deleter.go
- pkg/storage/mongo/checker.go
- pkg/storage/mongo/deleter.go
- pkg/storage/rdbms/checker.go
- pkg/storage/rdbms/deleter.go
- pkg/storage/storage_tests/module_storage/storage_test.go
This PR touches lots of files, but each one only has a few mechanical changes.
Note: I did `Exists` and `Delete` at the same time since every `Delete` function calls `Exists`. This way, we can avoid having this PR add `context.TODO()` everywhere and needing another PR to update those lines again.
Part of #174.
> storage: add context to storage.Exists and storage.Delete

- cmd/olympus/actions/app.go
- cmd/proxy/actions/app_proxy.go
- pkg/config/module.go
- pkg/download/version_zip.go
- pkg/errors/doc.go
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/log/entry.go
- pkg/log/log.go
- pkg/paths/path.go
Fixes https://github.com/gomods/athens/issues/275
Todo: write tests for the errors package and the logger's SystemErr method. 
I'd like to gather some feedback first before writing the tests. 
Things to look out for: 
1. I updated our logger to be "Athens' Errors Friendly" using the SystemErr method.
2. I updated download.VersionZipHandler to use pkg/errors, this is so you can check out what it's like to use the package. 
3. ~I'm using a copy of cmd/go's semver validation to determine whether a string goes into the Version field. We can use Mastermind's package instead (as suggested by @arschles) but we need to confirm that they both agree to the same semver rules (so far I know cmd/go enforces a "v" prefix while Mastermind does not). We can also avoid semver validation by just creating …
> Athens: introduce pkg/errors

- DEVELOPMENT.md
After following the setup guide in `DEVELOPMENT.md`, I still ran into an issue running tests:
```
ERRO[0000] Error: exec: "mysql": executable file not found in $PATH
```
Turns out `mysql` must be installed locally for `buffalo` to work. This PR adds that dependency to the bootstrap guide.
> Specify mysql should be installed as part of development bootstrap

- pkg/download/list.go
- pkg/download/version_info.go
- pkg/download/version_module.go
- pkg/download/version_zip.go
I don't know a ton about buffet and the opentracing library, but I saw that we're calling `defer sp.Finish()` in other parts of the code, so I figured we should do it here too.
cc/ @manugupt1 @robjloranger
> Finish spans in the download handlers

- .travis.yml
- CONTRIBUTING.md
- DEVELOPMENT.md
- Makefile
- scripts/check_deps.sh
- scripts/check_gofmt.sh
- scripts/check_golint.sh
- scripts/get_buffalo.sh
- scripts/get_dev_tools.sh
- scripts/test_unit.sh
* Extract the commands from `.travis.yml` into `./scripts/`
* Add targets to our make file to run groups of scripts
* Changed the buffalo install so that it doesn't do all it's dirty work in the repo repo, because it modifies existing files like our license and readme
* Add a contributing guide that explains our new make targets
> Make it easier to run all the same commands that Travis does 

- pkg/module/disk_ref.go
- pkg/module/disk_ref_test.go
- pkg/module/go_get_fetcher.go
- pkg/module/go_get_fetcher_test.go
This PR addresses https://github.com/gomods/athens/issues/329
Adding info about the root dir and module name to the diskRef and adding the `getPackagePath` function to construct the path to the cached module seemed the cleanest way to achieve what was desired - though I'm open to suggestions for a cleaner implementation :)
Edit - #329 was closed in favor of #318
> Ensure diskRef cleans up everything in it's own GOPATH

- cmd/olympus/actions/app.go
- cmd/proxy/actions/app_proxy.go
- pkg/download/goget/goget.go
- pkg/download/goget/goget_test.go
- pkg/module/go_get_fetcher.go
- pkg/module/go_get_fetcher_test.go
* Using `which gobinary` to verify whether the given binary exists, and if its invalid application exits. 
* Fixes instantiation of fetcher in each `(gg *goget) Version()` call.
Closes #372.
> Goget Fetcher should error out if gobinpath is not valid

- cmd/proxy/actions/storage.go
- pkg/config/env/gcp.go
- pkg/storage/gcp/gcp.go
Update constructor and its doc to reflect that Cloud Storage credentials can be obtained automatically by either being logged in to gcloud, being inside GCP, or having the GOOGLE_APPLICATION_CREDENTIALS set.
> GCP: get credentials implicitly

- scripts/check_deps.sh
Response to failed test here: https://github.com/gomods/athens/pull/387
Failed on master arg being ambiguous which happens when the branch is unknown/not fetched.
> Fetch origin master in order to do deps check

- .travis.yml
- CONTRIBUTING.md
- Makefile
- scripts/get_dev_tools.sh
- scripts/test_e2e.sh
* Add `./scripts/test_e2e.sh` which builds a go program that relies on go modules using GOPROXY.
* Add `make test-e2e` target and document it. It's important to run `make setup-dev-env` once, before running the tests.
* Use the same setup for travis and local development for the storage services
Closes #353
> Run E2E tests during CI

- pkg/download/goget/goget.go
- pkg/download/goget/goget_test.go
- pkg/download/goget/test_data/no_mod_file.golden
- pkg/download/goget/test_data/upstream_mod_file.golden
This PR introduces GitHub integration tests to our pkg/download/goget Protocol. This tests that goget is getting the right version data from live repos especially /list and /latest.
I've created a new organization: github.com/athens-artifacts to store dummy repositories. Please ping me if you'd like write access to it.
Fixes #340
> Download: test against controlled repositories

- cmd/olympus/actions/app.go
- cmd/proxy/actions/app_proxy.go
- pkg/download/get_module_versions.go
- pkg/download/handler.go
- pkg/download/latest.go
- pkg/download/list.go
- pkg/download/version_info.go
- pkg/download/version_module.go
- pkg/download/version_zip.go
Every HTTP request should carry a `log.Field` instead of a `*log.Logger`. A log.Field carries request-specific key-val pairs such as: (http-method, http-path, http-url) and more useful things as we see them fit (such as tracing IDs). 
This means that we can't just pass a *Logger instance to the handlers because we will have to repeat ourselves 5 times (or as many times as we have handlers really). 
This PR abstracts the creation of `*log.Logger` -> `log.Field` without having to magically pass things through buffalo middlwares/Context. 
Fixes https://github.com/gomods/athens/issues/328
> Download: introduce sane Entry defaults

- Makefile
Also changing docker repo to `gomods`
I found this was missing during my helm work (https://github.com/gomods/athens/pull/430)
> adding a docker build target for the proxy

- Makefile
Sorry I got click happy, I wanted to revert and reopen the PR. But apparently l I don't know how to GitHub.
I noticed the non `PHONY` target was missing after I merged. #454
> Fix: Revert "adding a docker build target for the proxy (#454)"

- CONTRIBUTING.md
- DEVELOPMENT.md
- cmd/proxy/.env
- scripts/test_unit.sh
The commit chages behaivour of `make test-unit` by adding sourcing of
env vars. Documentation is updated to provide more clarity on how to run
unit tests.
> Bring more clarity on how to run unit tests

- cmd/proxy/actions/filter.go
- cmd/proxy/actions/filter_test.go
- pkg/module/filter.go
- pkg/module/filterRule.go
- pkg/module/filter_test.go
As agreed on #473 Direct is more descriptive name for filter. 
Therefore changing `Private` -> `Direct`
changing rule syntax: `P github.com/a/b` -> `D github.com/a/b`
Fixes #473
> Rename Private filter to Direct

- cmd/proxy/.env
- cmd/proxy/actions/storage.go
This makes it easier for someone to try out or just run the proxy by executing the binary without further environment setup.
> Default to in-memory storage for the proxy

- cmd/olympus/actions/app.go
- cmd/proxy/actions/app.go
Buffalo was creating an internal worker if opts.Worker was nil, and it was logging nil things. So worker is for now turned off so peeps are aware that it's not being used.
> Athens: turn off worker to avoid nil logs

- .travis.yml
- DEVELOPMENT.md
- docs/content/faq.md
- docs/content/intro/components.md
- pkg/download/goget/goget.go
- pkg/download/goget/goget_test.go
- pkg/storage/rev_info.go
RevInfo updated to match go upstream
> // We want to canonicalize to .info files with those fields omitted
By those fields meant: Name and Short
https://github.com/golang/go/blob/daeb0b4f538872a37787626816c47afcf71bfd2c/src/cmd/go/internal/modfetch/cache.go#L312
Looks like @latest is according to specs now, 
retrieves latest version, in case of no version pseudo version is retrieved
> Updated to go1.11rc1

- cmd/proxy/actions/app.go
- pkg/config/env/ssl.go
HTTPS should not be forced on Production environments for the Proxy because the Proxy can potentially run inside Google App Engine, GKE, or other platforms where certs are provided by the platform and your app doesn't need to have its own certs.
> Proxy: make Force SSL configurable

- cmd/olympus/actions/app.go
- cmd/olympus/actions/health.go
- cmd/proxy/actions/app_proxy.go
- cmd/proxy/actions/health.go
While trying to deploy the Proxy behind a domain name, Kubernetes' Ingress controller requires a health check endpoint to proxy a domain name to a backend. But regardless of that, we should have a dedicated healthcheck anyway. In the future, we can have the healthcheck ping the storage and other dependencies to get back a true health check :)
> Athens: add health check endpoint

- pkg/storage/mem/mem.go
At the moment each mem.NewStorage() will create own instance of afero.Fs which means if we do:
```
s1 = mem.NewStorage()
s1.Save(mod@ver)
```
then `s2.Get(mod@ver)` will return `nil` because `s2` has it's own in-mem file system.
This can be confusing because every other storage would return the module.
> Ensure there is only one in-mem storage instance

- cmd/proxy/actions/app.go
- cmd/proxy/actions/netrc.go
- pkg/config/env/netrc.go
We need to have a way to authenticate a deployed Proxy to have access to private repos (that's kinda the whole point of the Proxy lol). 
Currently, .netrc is the easiest way possible but we can't mount it directly to the home directory because Kubernetes would remove other files in ~ causing our internal goget to be confused. 
I'd like to open another issue to use the Linux in-memory authentication as suggested [here](https://confluence.atlassian.com/bitbucketserver/permanently-authenticating-with-git-repositories-776639846.html)
> Proxy: add NETRC file mount

- .gitignore
- pkg/download/handler.go
- pkg/middleware/cache_control.go
- pkg/middleware/cache_control_test.go
- pkg/middleware/middleware_test.go
Certain Download Protocol handlers must be careful not to cache anything down the network. In particular, /list and /@latest because they always depend on upstream and are subject to change in real time. 
This PR adds a middleware to set custom Cache-Control header and adds it to the two handlers that need it.
> Proxy: add cache-control middleware

- .gitignore
just starting to use Goland as im struggling with vscode performacne, and it adds this .idea folder so I'm not sure if it's normal for people to add it or ignore it.
> Athens: add .idea to gitignore

- Gopkg.toml
We have a pkg/errors in gopkg.toml that is not used anymore. We are removing this to remove dep ensure warnings.
Fixes #552
> Remove unused pkg/errors from gopkg.toml

- pkg/storage/mongo/getter.go
- pkg/storage/mongo/lister.go
In mongo.Zip, KindNotFound is not included which ended up making certain builds fail because we told the donload.Protocol it was an unexpected error, instead of a NotFound error so it ended up returning 500 to cmd/go instead of fetching the module from Upstream.
> pkg/storage: ensure mongo returns KindNotFound

- pkg/download/goget/goget.go
- pkg/download/goget/goget_test.go
- pkg/module/disk_ref.go
- pkg/module/disk_ref_test.go
- pkg/module/go_get_fetcher.go
Go sends up to 10 protocol commands concurrently, and so if you have the following deps
```
import (
"github.com/user/pkg"
"github.comuser/pkg/subpkg"
)
```
Then go might send both requests at the same time, and you'll see weird errors such as `git ls repository already exists`. 
Therefore, we should treat `go list -m` just like `go mod download` in that each time they get a fresh empty GOPATH so that they don't on each other. And make sure we remove it after.
> pkg/download/goget: ensure each List func gets its own GOPATH

- .travis.yml
- Makefile
- scripts/push-docker-images.sh
🚨 I am testing this out on my own repo and registry. Will remove the WIP once it's working as intended.
___
master builds publish using the git describe output  as the immutable tag and canary for the mutable tag. Examples:
gomods/proxy:abc1234
gomods/proxy:canary
tagged builds publish using the tag as the immutable tag, which is usually going to be a semver value and with latest for the mutable tag.
Examples:
gomods/proxy:v1.0.0
gomods/proxy:latest
branch builds publish using the git describe output as the immutable tag and the branch name for the mutable tag. Examples:
gomods/proxy:def4567
gomods/proxy:beta-1
Suggestions welcome on exactly where to document this for others. @jeremyrickard is writing install docs that are going to have people use the images, but it would be nice to also …
> Deploy docker image during CI

- scripts/ps/test_e2e.ps1
Sets the ENV VARs to the original values or removes them if they didn't exist.
> Powershell - clean up ENV after tests

- docs/config.toml
This just disables the little copy to clipboard button in our inline code blocks.
closes #510
> disable inline copy to clipboard

- CONTRIBUTING.md
- Makefile
- scripts/check_conflicts.sh
This new script returns exit code 1 when any files other than '*.go,go.mod,go,sum' contain merge conflict artifacts. `<<<<<<<HEAD`, `=======` or `>>>>>>>branch-name`.
It skips the mentioned files as those will be caught during linting and dependency checks.
closes #273
> No conflicts

- init.ps1
- scripts/check_deps.sh
- scripts/ps/check_deps.ps1
- scripts/ps/check_gofmt.ps1
The `scripts/ps` directory was missing `check_deps.ps1`, and had a major typo in `check_gofmt.ps1` that prevented a successful run.
Fixed a couple of typos in related files while I was at it.
> Fix powershell scripts

- .goreleaser.yml
This will have go releaser still generate the binaries on a new tag but only _draft_ a new github release. Leaving it up to a maintainer to read over, edit if necessary, and then publish a release.
I think this will be better than just publishing the generated releases as we may add a message to the community or edit out extra commit messages that are not very relevant, creating a more readable and useful release notice.
> change go releaser to create draft releases

- init.ps1
- pkg/module/go_get_fetcher.go
- scripts/ps/create_default_config.ps1
- scripts/ps/test_e2e.ps1
Currently proxy doesn't work on Windows 10.
This PR fixes this issue by adding required ENV variables
It also updates the `test_e2e` powershell script so that it uses `go build -mod=vendor` just like the bash version
> Fix for Windows 10

- netlify.toml
I used a 303 status code as the pages currently hosted should always be requested at `docs.gomods.io` not any of the other possible domains. `gomods.io | gomods-athens.netlify.com`.
will close #651
> redirect other domain requests to docs.gomods.io

- README.md
Thanks for suggesting this @timraymond!!!
I've submitted Athens to CodeTriage and added the codetriage badge
I also:
- shifted the badges above the athens logo
- shifter the "welcome gophers" header above the logo.
- changed "welcome gophers" to "welcome to athens, gophers"
Fixes https://github.com/gomods/athens/issues/656
> Adding CodeTriage badge

- pkg/module/go_get_fetcher.go
Pass the `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` environment variables to the go command in `go_get_fetcher`.
> Add HTTP_PROXY environment variable to go_get_fetcher

- pkg/errors/gocmd.go
Not sure why some builds fail and some succeed.
> pkg/errors: add comment to exported function

- config.example.toml
- pkg/config/parse.go
- pkg/config/parse_test.go
- pkg/config/proxy.go
- pkg/config/storage.go
I'm deploying the new Athens Config stuff and so I'm cleaning up things: 
1. Remove unused config fields 
2. Remove the `validate:""` as it's not needed. 
3. fix some "required" fields. 
There's a few more stuff coming up but they require some code change, so keeping the PRs small.
> Clean up Config

- cmd/proxy/.env
- vendor/github.com/gobuffalo/suite/.gitignore
Now that we have a config file, dotenv is not necessary to be checked. 
I'm thinking more about the development flow and how we should tweak config things while writing code locally. And might open an issue or two for the new config flow.
> Git ignore .env file

- cmd/proxy/actions/app.go
I believe this got deleted by accident when peeps removed the Redis worker stuff. Buffalo still spins off a Simple Worker unless we explicitly set it off in the options.
> Ensure Simple Worker is off

- cmd/proxy/Dockerfile
A couple of suggestions made by @tnextday in a previous PR: 
1. Change `ENTRYPOINT` to `CMD` 
2. Give the Proxy binary a less generic name.
> Dockerfile updates: better naming and prefer CMD

- cmd/proxy/main.go
We should make onboarding very easy, and asking people to create their own config off the bat is very difficult. 
The config.example.toml works out of the box (and we should always keep it so).
> Make example config the default for dev

- cmd/proxy/actions/app.go
These errors were reported by Brent on Slack.
Are there any additional setup requirements with the tracing stuff that has been added recently? Ran e2e tests locally today and got a new error:
```ERRO[0000] Exporter URL is empty. Traces won't be exported```
Since tracing is not a hard requirement. They should just be an info log for the user so that when they see it they can add it to their system.
> Change error log level to info logs when tracing is not initialized

- scripts/test_e2e.sh
Noticed when running the e2e tests locally that it creates an `athens-proxy` binary that gets left as an untracked file after the tests finish. Thought it would be good to clean up the file during the test teardown.
> Clean up e2e binary

- docs/content/faq.md
Docs for Observability. I could not figure out a better place to put it. If you can suggest a good one, that will be awesome!
> Add observability docs how-to in faq

- pkg/download/protocol_test.go
The GoMod test fails because of unix/windows line endings difference.
this PR fixes it by ignoring the line endings.
> Fix tests on Windows

- pkg/storage/storage_tests/module_storage/storage_test.go
I had a failing test due to some stale data in the mongo store. I'm not exactly sure how it happened.
This PR will clean up the stores before the tests are run to avoid any stale data causing failure.
> Clean up store before test.

- cmd/olympus/main.go
Starting buffalo for Olympus gives error:
```
buffalo dev
[POP] 2018/10/05 14:12:19 error - Unable to load config file: unable to find pop config file
buffalo: 2018/10/05 14:12:19 === Rebuild on: :start: ===
buffalo: 2018/10/05 14:12:19 === Running: go build -v -i -tags development -o tmp/olympus-build  (PID: 6918) ===
buffalo: 2018/10/05 14:12:20 === Building Completed (PID: 6918) (Time: 809.277611ms) ===
buffalo: 2018/10/05 14:12:20 === Running: tmp/olympus-build (PID: 6965) ===
2018/10/05 14:12:20 open ../../config.toml: no such file or directory
buffalo: 2018/10/05 14:12:20 === exit status 1
2018/10/05 14:12:20 open ../../config.toml: no such file or directory
===
```
Reference the development config file …
> Use config.dev.toml by default for Olympus

- pkg/download/protocol.go
- pkg/stash/stasher.go
- pkg/stash/with_pool.go
- pkg/stash/with_singleflight.go
Sometimes it's hard to read `s.s` 
single letter props replaced with more meaningful names so
`s.s` becomes `s.storage` and `s.stasher` respectively.
> Updated single letter props in stasher

- docs/content/_index.md
- docs/content/contributing/community/_index.md
- docs/content/contributing/community/developer-meetings.md
- docs/content/contributing/community/participating.md
- docs/content/contributing/maintainers/_index.md
- docs/content/contributing/new/_index.md
> The Athens development meeting happens weekly but nobody knows where to
> find it.. 
I felt that the current organisation of these pages wasn't
easily readable so have sorted the community pages separately from
those on say using Git or GitHub. I took a lot of the content from the
google doc so I altered it slightly so it fits with the voice of the
current document.
The new structure is:
Contributing > The Athens Community > Participating in the Community
Contributing > The Athens Community > Developer Meetings
**Fixes issue:  #[730]**
Signed-off-by: Chris M <millscj01@gmail.com>
> Include weekly development meetings within documentation

- docker-compose.yml
We have a docker compose file that has jaeger as self documented tracer. It will be nice to have data dog as well in the list
Updated the docker-compose file with datadog images and minimal env var from docs.
> Add datadog to docker-compose as well

- config.dev.toml
- pkg/config/mongo.go
- pkg/config/parse_test.go
- pkg/storage/mongo/mongo.go
Certificates can be used in multiple ways
A) They can be in the system cert pool for which the support is already there fixed in #756 
B) They can be appended to a cert pool that is acquired from the certificate directly within the app.
C) The insecure flag can still be passed for dev and test purposes.
Pass an env var to determine if insecure flag is passed or not.
Fixes issue:  #540
Fixes #540
> Support custom ca's and make insecure as part optional default being false

- docs/content/try-out.md
Try it out documentation is not working due to relative path of config file. Also it does not show the repo working outside the GOPATH.
Updated "try it out" documentation to run proxy outside the GOPATH and match expected output.
Also fixes minor formatting issues.
**Mention the issue number it fixes or add the details of the changes if it doesn't has a specific issue.**
Fixes #780
> Document trying proxy outside the GOPATH

- docs/content/contributing/community/participating.md
I noticed in the [participating docs](https://docs.gomods.io/contributing/community/participating/) that in the last bullet point there's no space between the contributor covenant link the `(english version)`
So I added a space 😄
> adding a space before "(english version)" in the contributor docs

- pkg/download/upstream_lister.go
Fixes a comment to remove a mention of deprecated Olympus
> Remove olympus mention in doc comment

- CONTRIBUTING.md
First time contributors should be given as much info as possible about the best ways to go about contributing to open-source. Often when stepping into a new world it's nice to have a step-by-step guide on what to do. This PR is adding in a link in the contributing docs to the first-contributions docs which is aimed to help first time contributors out.
Fixes #794
> link to first-contributions docs in contributing docs

- cmd/proxy/actions/home.go
The previous homepage (i.e. `GET /`) returned the JSON string `Welcome to the Athen Proxy`
This just fixes the typo :smile:
No particular issue fixed here
> Improve the home page

- CONTRIBUTING.md
- docs/content/contributing/new/development.md
Copies the development doc over to the new contributor section. Not sure if this is the best way to do it though; having two copies of the same thing in two locations. Is there a way to create a doc page that links automatically to development.md?
Fixes #836
> adds development.md to new contributor section

- CONTRIBUTING.md
- cmd/proxy/actions/app.go
- config.dev.toml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/proxy.go
We have 2 variables in our config `FilterFile` and `FilterOff`. This can create confusion to users when they have a FilterFile but have set FilterOff. We can actually look if `FilterFile` has been set or not and determine if a `FilterFile` needs to be found.
Remove `FilterOff` from `config.dev.toml`
No particular issue, but a general clean up.
> Remove FilterOff from the env var

- cmd/proxy/actions/auth.go
Windows expects netrc file to be named "_netrc" instead of ".netrc" 
If we;re on windows we will use `_netrc` orherwise `.netrc`
`.hgrc` should be fine 
Fixes #832
> Netrc for windows

- DEVELOPMENT.md
- Makefile
- docs/Dockerfile
Following yesterdays development meeting they discussed running `hugo` locally. There's no official Dockerfile so lets go and create one!
> In today's dev meeting (November 1, 2018) we discussed having documentation on how to run the documentation site locally. #851 talks about that.
I've added a simple Dockerfile tied down to the current version of alpine and hugo. The hugo version can be bumped with the environment variable `HUGO_VERSION` although this might become a chore so I could write a helper script to bump this automatically.
I also changed the Makefile to build the container which we can link up to CI/CD. I can also do this as part of this ticket if needed?
I added some simple documentation to …
> Add a Dockerfile for Hugo

- docs/content/contributing/new/docs.md
Include the new running the docs thing in our docs website.
> docs: refer to custom hugo image in docs website

- docs/content/contributing/_index.md
Found a broken link in the docs. It looks like the previous "community roles" page was renamed "participating". It's on the [contributing page](https://docs.gomods.io/contributing/) when clicking "how to participate in the Athens community".
I updated the markdown link to point to `participating.md`. @marwan-at-work I used the new guide for making docs contributions. I had been wondering how to run that locally! Thanks!
> Fix broken link

- docs/content/faq.md
I found a link in our markdown docs that lead to a 404. 
Correct the link
No issue
> Fix link that leads to a page that does not exist

- cmd/proxy/actions/app.go
- pkg/middleware/filter.go
- pkg/middleware/middleware_test.go
- pkg/module/filterRule.go
After we went away from workers and redesigned data flow, filters stayed one step behind.
This PR brings them even and adds a bit different meaning to filtering keywords considering new data flow.
Change is following
- Include:
- Treats module as it should be without using filter functionality used to reset parent behavior change
- Exclude:
- Results in exclusion of the module entirely
- Direct:
- Goes to the upstream proxy without consulting a local storage
- Before: went to VCS  directly without consulting Olympus as a backup, treated module as a private repo
Filtering middleware moved after auth. So we don't tell whether we treat or we don't particular modules for unauthenticated users.
Removed handling of …
> Filter: fixing after refactoring

- docs/Dockerfile
Added the multi-stage build in order to avoid all the `rm` commands and just copying `hugo` binary to a fresh image.
Kept the packages as I'm not sure if they're needed "in the long run".
For debugging purpose, I kept the `ENV` values, however if needed, the `builder` part could be changed to the following for "always" up to date Hugo version:
```Dockerfile
FROM alpine:3.8 as builder
RUN apk add curl wget jq
WORKDIR /tmp
RUN curl -s https://api.github.com/repos/gohugoio/hugo/releases/latest | jq -r ".assets[] | select(.name | contains(\"Linux-64bit.tar.gz\")) | .browser_download_url" | grep -v extended | wget -qi -
RUN tar -xzf hugo*.tar.gz
```
Mention briefly how …
> [Docs] Added mutli-stage build to Dockerfile

- DEVELOPMENT.md
We should mention that you don't need to install Buffalo to run Athens locally. #allYouNeedIsGo
Later this week, I will also add the "all you need is Docker" part. 
Fixes https://github.com/gomods/athens/issues/872
> Update docs for those struggling to set up buffalo

- pkg/download/handler.go
Use the log entry stored in the buffalo context via middleware in pkg/download so that we're not creating log entries from the request in multiple places. #844 creates the middleware but the download package is still creating it's own entry for the protocol handlers. This PR updates that logic. 
Use the existing `LogEntryHandler` to extract the log entry from the buffalo context and pass it to the protocol handlers.
Fixes #809
> extract log entry from context in pkg/download

- README.md
- docs/static/meeting-icon.svg
It's not really that clear that we have developer meetings every week. It'd be cool if 
>Info on our weekly dev meetings could be more prominent.
Just a simple table with an icon. It's a nice to have.
Suggestions welcomed for placement of said table and any content changes.
Fixes #875
> Make the weekly meeting more prominent in the README

- charts/proxy/templates/deployment.yaml
When you `helm install` the proxy into a Kubernetes cluster, the proxy doesn't start up. That's because the helm chart sets `ATHENS_MONGO_CONNECTION_STRING` but the code looks for `ATHENS_MONGO_STORAGE_URL`. The result is that each proxy pod never starts serving because it tries to connect to a mongoDB server running on localhost.
I changed `ATHENS_MONGO_CONNECTION_STRING` to `ATHENS_MONGO_STORAGE_URL` in the helm chart.
@marwan-at-work could we get this into the `v0.2.0` release by chance?
> using the proper env var name for the mongo URL

- Makefile
The current `makefile` target for `docker-push` also calls `docker`, which calls `proxy-docker` which builds the image. This is redundant as the script called in the target for `docker-push` also builds the image with the proper tags and args.
Removed the call for the target `docker` from the target `docker-push`.
> makefile target for pushing docker image should not call build target

- Makefile
- charts/proxy/Chart.yaml
- charts/proxy/values.yaml
- docs/content/configuration/authentication.md
- docs/content/install/_index.md
- docs/content/install/shared-team-instance.md
- docs/content/walkthrough.md
- init.ps1
- scripts/push-docker-images.sh
We renamed the project to Athens but didn't rename the docker image.
* I've manually retagged our docker image from `gomods/proxy` to `gomods/athens` for the release v0.2.0
* I've updated the CI to push using the new tag going forward.
* I've switched from using the stable tag to using latest, to fit our documentation and docker standards.
* I've updated the helm chart to match and also bumped the tag used in the chart with our latest release (v0.2.0).
* I've updated the documentation.
N/A
> Rename docker image

- docs/content/install/_index.md
- docs/content/install/shared-team-instance.md
Prevent confusion over which docker tags to use
* I've documented the tags on our Install page
* Warned people to pick a specific version
* Updated our docker hub page to alert that [gomods/proxy is deprecated](https://hub.docker.com/r/gomods/proxy/), and again [explain the tags](https://hub.docker.com/r/gomods/athens/).
YOLO
> Document our docker tags

- .travis.yml
- Makefile
- pkg/storage/gcp/gcp_test.go
In our CI we download and run the minio binary which takes time + we have to keep it in sync with docker-compose file
Use docker-compose instead
No issue for that.
> use minio docker img on travis

- docs/themes/hugo-theme-learn/layouts/partials/custom-footer.html
Add better links from the docs back to the Github repo.
Edited the docs template to include the ribbon
Possible fix for #804
> Adds Github ribbon link to docs

- pkg/config/config_test.go
os.Chmod on windows is not supported which led to CI failure. Ref: https://github.com/golang/go/blob/master/src/os/os_test.go#L1031
Skip test for windows as done by the go source code as well so that CI does not fail
> skip test for chmod on windows

- docs/content/configuration/storage.md
As we droped timeout from `config.dev.toml` ( #928 ) for storages, we should also remove them from documentation
Removed timeouts from storages configuration
Fixes:#
> Remove timeouts from Storage documentation

- docs/content/contributing/community/developer-meetings.md
The zoom URL has changed a few times and when it does, we have to update it on the docs site (and also on the [Athens agenda doc](https://docs.google.com/document/d/1xpvgmR1Fq4iy1j975Tb4H_XjeXUQUOAvn0FximUzvIk/edit#))
I've created a [short link](https://aka.ms/athensdevzoom) and put it into the docs. Then, if the zoom link changes we can update the short link in one place.
> changing the zoom link to a shortlink

- MAINTAINER_RESOURCES.md
The maintainers group has been working to keep track of all the resources our community uses (i.e. Zoom for dev meetings, YouTube for weekly dev meeting recordings, Medium blog, and so on)
I've created a markdown file with a table in it to keep track of all of our resources and the maintainers with access to each resource.
We'll first use this table to make sure each maintainer has access to everything.
Then, when we add new maintainers, we'll update the table and use it to ensure that the new person has access to everything they need.
Finally, if we add/remove a resource that the community uses, we'll edit the table as appropriate 😄 
**Mention the issue number it fixes or add the details of the changes if it …
> Maint resources

- config.dev.toml
A question was asked about how to prefixing : in the PORT
Make it clearer by adding docs for the users
> Add note that : should be prefixed for port

- pkg/download/protocol_test.go
One of the core strengths of proxy is that when the download protocol fails, the storage should be immutable
This adds a test to show that it is indeed immutable.
Fixes #946
> Add test when go mod download fails

- pkg/module/go_get_fetcher.go
Add the ability to manually point out a git configuration file. This is needed to be able to use private repositories that uses ssh instead of https, see #959 
There is also a `GIT_CONFIG` env but it seems like only `git config` uses that one:
https://github.com/git/git/blob/965798d1f2992a4bdadb81eba195a7d465b6454a/builtin/config.c#L601
Fixes #959
> Propagate HOME env to go command execution

- README.md
We didn't have a badge that shows how many times our image was pulled from docker hub, and I love badges
I added the badge and re-ordered the badges
> Adding badge for docker pulls

- docs/content/_index.md
>The link to https://docs.gomods.io/public_proxy from https://docs.gomods.io/ results in a 404 error.
Quick content change to reference the address of the proxy we host.
Fixes #915
> Correct reference to public proxy.

- pkg/storage/mongo/lister.go
Mongo lister fetches binaries. This might make queries slower while running over cluster
Fetch only versions as that is the only output that is required.
> Only fetch versions while list is called

- docs/content/intro/protocol.md
**What is the problem I am trying to 
#978 
find typo words `bellow`
```
$ grep -rin bellow .
```
and
convert  with checking : `:%s/bellow/below/gc` in vim
Fixes #978
> Fix typo in protocol.md #978

- docs/content/intro/protocol.md
We were missing a `the` in the protocol docs
I added one 😄 
This is a follow-up from #987 
> fixing typo in protocol docs

- pkg/config/config.go
@manugupt1 mentioned we can do this via git, but for now I'd love us to merge this because it's really annoying for the Developer Experience, especially if they're playing with Athens for the first time.
> only check config perms in production

- config.dev.toml
- pkg/config/config_test.go
Returned TraceExporter to be an empty string because when you have "jaeger" and Jaeger is not set up, we keep getting the following logs which is not good: 
`2018/12/21 17:28:23 Error when uploading spans to Jaeger: Post http://localhost:14268/api/traces?format=jaeger.thrift: dial tcp [::1]:14268: connect: connection refused`
> Revert TraceExporter Default

- cmd/proxy/main.go
Print a start up log that mentions the port Athens is running on.
> cmd/proxy: print port at server start

- Makefile
- init.ps1
Replace `buffalo build` with `go build` since we don't have any assets to bundle
> CI/CD: replace buffalo build with go build

- pkg/storage/mongo/mongo_test.go
This seems like reverting a regression because our storage tests are set up such that they "skip by default, unless explicitly set by variable". 
Let me know if I'm missing something.
> mongo: use explicit URL for testing

- pkg/download/addons/with_pool_test.go
Wrong number printed in error message in with_pool_test.go.
Fixes the problem by introducing a new variable.
> pkg/download/addons: fix test error msg in TestPoolLogic.

- cmd/proxy/actions/basicauth.go
Kubernetes users have easily missed to pass auth headers to their livenessProbe and readinessProbe, and K8s doesn't really say much. We should log a warning if the user passes does not pass correct authentication to our /healthz endpoint to help such users figure out what is wrong.
> basicauth: log warning on healthz

- config.dev.toml
- pkg/config/s3.go
- pkg/storage/s3/s3.go
Athens does not pick up aws "ambient" role credentials when run in ec2, ecs or fargate containers.
A new variable `UseAmbientCredentials` (or `$AWS_USE_AMBIENT_CREDENTIALS`) is added. If `false`, and `Key` and `Secret` are defined then the aws config is built as it was previously. If `true` then just a default `aws.Config` is used with Region provided. This will use ec2/ecs credentials (in addition to using the `~/.aws/credentials` that were previously used).
The reason the new variable is required is because ec2/ecs systems will also define `$AWS_ACCESS_KEY_ID` and `$AWS_SECRET_ACCESS_KEY`.
> Use ambient aws credential provider for s3

- docs/content/configuration/filter.md
- pkg/middleware/filter.go
- pkg/middleware/middleware_test.go
- pkg/module/filter.go
- pkg/module/filter_rule.go
- pkg/module/filter_test.go
Increase the granularity of module filtering to include version matching.
A comma-separated list of version filters is parsed from the filter rule, separated from the module by a space.  These version filters are applied using a prefix match, similar to the module filtering.  
Documentation has been updated, with an example filter file using version filtering.
Fixes #1045
> Version filtering

- config.dev.toml
- pkg/config/config_test.go
Update the GoGetWorkers documentation to be clear about what it does under the hood, I also lowered the number to a more sane default...doing 30 git clones at the same time will more likely run you out of resources.
> pkg/config: Update GoGetWorkers default/docs

- pkg/config/config.go
Having Athens be okay to run without a config file makes the developer experience a little bit nicer since you can just run it as a standalone binary. 
Therefore, it's okay to make it the maintainers' responsibility to make sure that our two copies of the defaults are absolutely identical (the defaults in config.go vs the defaults in config.toml). 
We can potentially run a script to compare the two defaults and fail the pipeline on PRs, but for now manual checking is alright.
> Keep code defaults and config.toml defaults the same

- cmd/proxy/Dockerfile
Now that the Release Candidate is out for 1.12, it's good that Canary users can test it out and so that they can catch any backwards-incompatible changes in Go Modules early on (i.e. the checksum mismatch issue)
> Use Go 1.12rc for Docker Image

- cmd/proxy/Dockerfile
- ``apk update`` fetches the index and saves it locally
- ``apk add --update`` fetches the index and installs the requested
packages
> Dockerfile: remove redundant call to apk update

- pkg/config/config.go
Same as a previous PR: https://github.com/gomods/athens/pull/1062
Will make sure that using and not using a config file have no side effects
> pkg/config: make StatsExporter consistent with config.toml

- pkg/config/config.go
- pkg/config/config_test.go
Fixes #1037.
envconfig can't actually support that use case, and because athens was
using the `default:` tag only for the port field, handling this manually
is the easiest and functional solution.
> pkg/config: make sure envconfig doesn't override config values for port

- docs/content/install/install-on-aci.md
- docs/content/install/shared-team-instance.md
There were no docs on how to install Athens on [Azure Container Instances](https://cda.ms/KR)
I added a document describing how to install Athens on Azure Container Instances
Fixes https://github.com/gomods/athens/issues/57
> Adding a document for installing Athens on ACI

- .gitignore
If you run Visual Studio Code, your editor might create a `.vscode` directory under this repository. It has settings specific to your preferences and it's better that we keep our editor preferences our own, and not have this project impose them on you 😄 
I added `.vscode` to the `.gitignore` file
None
> ignoring vscode local settings dir

- config.dev.toml
- go.mod
- pkg/config/gcp.go
- pkg/storage/gcp/gcp.go
Fixes https://github.com/gomods/athens/issues/1087
> storage/gcp: allow json key to be used for GCS access

- config.dev.toml
- pkg/storage/gcp/gcp.go
@leitzler suggested that we use base64 for a json inside a string to avoid any weird parsing errors. The only parsing hack I had to do was to escape new lines "\\n" -- however, it seems that some CIs give even weirder errors such as: `private key should be a PEM or plain PKSC1 or PKCS8; parse error: asn1: syntax error: sequence truncated` 
So to avoid all of these possibilities, we'll just have to let users encode their own json key in base64 which shouldn't be a huge hassle hopefully.
> storage/gcp: use base64 for json key

- pkg/storage/fs/cataloger.go
- pkg/storage/gcp/cataloger.go
- pkg/storage/minio/cataloger.go
- pkg/storage/s3/cataloger.go
`go vet ./...` fails due to unkeyed values of similar types. This fixes it so that if/when we add `go vet` it should be happy.
> catalog: fix vet errors

- .travis.yml
- cmd/proxy/Dockerfile
Once go1.12 is up on Docker Hub, this can be merged so that we can release v0.3.0 ✌️
> build: switch to go1.12

- docs/content/install/_index.md
The docs don't say what happens if the upstream repository owner changes git tags, overwrites commits, deletes their repo, etc...
I added documentation that explains how Athens stores modules in write-once storage
Fixes #1054
cc/ @MMulthaupt - let me know if these new docs answer your question from #1054
I've left this as a draft PR for now, I'm going to wait for @MMulthaupt's answer before I promote it to ready to merge
> adding a section on immutability

- docs/content/install/install-on-kubernetes.md
The Kubernetes docs reference installing a helm chart from the local repository, but now that https://github.com/gomods/athens/pull/1097 is merged, they should install from the public repository
I updated the docs
Fixes https://github.com/gomods/athens/issues/1099
Follow-up to https://github.com/gomods/athens/pull/1097/files
cc/ @carolynvs can you let me know if these docs are right?
> Updating helm docs to point to the new helm chart repository

- config.dev.toml
Added a helpful documentation to let people know that the Basic Auth option is only temporary and not a great production solution :)
> config.toml: add cautionary note around basic auth

- pkg/download/version_zip.go
I run athens behind reverse proxy. Athens set content type `application/json` for .zip file.
So the reverse proxy will compress the .zip file to gzip/br (because it think that file is json) depends on client's accept-encoding.
Set content type to `application/zip` before send zip data.
> ZipHandler set content type

- .drone.yml
Copied Carolyn's Helm magic into its own Drone plugin here: https://github.com/gomods/drone-helm
This way, the Drone pipeline can publish helm charts from an upstream Docker image just like the rest of the pipeline.
> drone: add publish helm charts

- azure-pipelines.yml
Since Drone is now in place and tests almost all of our storages, there's no need for Azure Pipelines to run the same tests. All we need it for is that it's Windows compatible, and the biggest difference between Windows/Linux is the FileSystem so we should insure the regular tests pass on Windows and I'd say that's a pretty confident sign that things are working properly. 
Fixes https://github.com/gomods/athens/issues/1111
> ci/cd: remove bottlenecks from azure pipelines

- pkg/storage/compliance/tests.go
- pkg/storage/s3/checker.go
Currently our `storage.Exists` implementation checks only for the `mod` file. This can be problematic if i.e. `zip` or `info` uploads failed. 
I'm checking if the len of objects equals 3 (zip, mod, info)
Partially fixes #1032
> s3 Use no. of objects for Exists check

- docs/content/intro/components.md
The docs indicated that there are 4 components in the high level architecture,
but only 3 are described.
The right number is 3, so I've changed the docs from 4 to 3
cc/ @linuxsuren and @hihilary, since this was found in https://github.com/gomods/athens/pull/1128
> Changing high level arch. docs to indicate the right number of components

- azure-pipelines.yml
Azure pipelines uses g1.11 but Athens requires 1.12
Using windows containers on Azure Pipelines is slow - it takes around ~12min (8min just to pull the image) ref: #1126 
This PR uses chocolatey to install go 1.12 on the VM
> Azure Pipelines: use go1.12

- README.md
README.md shows build status for Travis.
Since we replaced it with drone.io, the status badge should be replaced as well.
> Replace travis build status with drone status

- pkg/module/go_get_fetcher.go
I noticed that Go treats SSH env vars in special case here: https://github.com/golang/go/blob/master/src/cmd/go/internal/get/get.go#L156
So we should be passing those environment variables.
> pkg/module: include SSH environments

- docs/content/configuration/upstream.md
Minor typo in command example
Replaced "/proxy" with "<path_to_athens>/proxy"
> Include path in the proxy command example

- docs/content/install/install-on-kubernetes.md
There's a link to the config file in the Kubernetes install docs 
(https://docs.gomods.io/install/install-on-kubernetes/), and the link has a line
number in it. The code in the config file has changed and now the link points
to the wrong line
I removed the line number in the link (so it points to just the file) and
instead just describes where the config field is.
Fixes https://github.com/gomods/athens/issues/1157
> Removing the line number from the config link

- pkg/storage/compliance/tests.go
The storage test harness had a typo in the log message for the clearBackend() call
I fixed the typo
> Fixing typo in storage compliance test harndess

- pkg/storage/compliance/tests.go
- pkg/storage/gcp/lister.go
- pkg/storage/s3/lister.go
I noticed that our `/@v/list` endpoint was adding versions that didn't exist for `github.com/gobuffalo/buffalo` which turns out to be a bug in our GCP lister because it was considering all modules that had the previous prefx so it took version from other mods like `github.com/gobuffalo/buffalo-plugin` 
Most of our backend implementations have this correct, but I believe Azure/S3 might have this incorrect as well. We should hopefully add those implementations in our CI soon
> storage/gcp: fix lister prefix

- pkg/config/config.go
I noticed that when there's no Config file provided, the environment variables don't override any of the defaults. According to config.dev.toml, all environment variables have more priority so we should make sure they do override the hard coded configs.
> pkg/config: ensure env vars override defaults

- config.dev.toml
- pkg/config/config.go
- pkg/config/config_test.go
Athens uses ATHENS_PORT to read the port value it needs to run on. However, a lot of cloud platforms recognize PORT by convention and would never know or add support for custom port environment variables. 
I added the flexibility to accept PORT environment in case ATHENS_PORT is not present and ensuring that the port adds a colon if it did not exist. 
Fixes https://github.com/gomods/athens/issues/1182
> config: accept PORT env + ensure colon

- Dockerfile.test
We should use 1.12 in our tests
> Use go 1.12 in Dockerfile.test

- pkg/module/go_get_fetcher.go
When running locally, it's convenient to use a user's ssh-agent. For
that to work, we need to propagate SSH_AUTH_SOCK.
Not all SSH keys are stored as files without passwords in `~/.ssh`. It is quite convenient to use `ssh-agent` (or `gpg-agent` in `ssh-agent` mode) to provide limited access to keys without having to enter the SSH key every time. (most notably when running on a workstation/laptop)
This is most useful when running `athens` as a docker container in the background.
`openssh` generally handles the `SSH_AUTH_SOCK` environment variable automatically, so if it is present in the environment of `go mod download`, ssh-agent-based public key auth should just work. …
> pkg/module: include SSH_AUTH_SOCK in go get env

- pkg/config/config.go
- pkg/config/config_test.go
Ensures that if the PORT doesn't have `:` it will add it. I added the logic and tests in a previous PR but this one makes the call now that it works well.
> pkg/config: ensure port format

- pkg/module/go_get_fetcher.go
This PR addresses #1192 and adds the lowercase version of unix Proxy environment variables. This makes Athens work the same way that the go binary does supporting both UPPER and lower case proxy environment variables.
> Fix for issue #1192

- cmd/proxy/Dockerfile
Athens runs `go mod download` which internally runs different VCS binaries such as `git` and `bzr`. 
Therefore, Athens doesn't have control over those binaries leaving defunct processes behind. 
The user can run the Athens docker container with `--init`, but chances are high that our users will miss to put this flag when they run their containers. 
From looking around the tini repo, I don't see any significant overhead or side effects that we should be aware of. But, we should definitely keep an eye out for those. 
Fixes https://github.com/gomods/athens/issues/1155
> Dockerfile: wrap athens with tini

- docs/content/faq.md
- docs/content/install/install-on-kubernetes.md
> There were some sentences in the "Is there support for monitoring and observability for Proxy?" FAQ that were written too informally.
> 
> Additionally, documentation for installing Athens on Kubernetes had duplicate directions.
> I re-worded the sentences and removed the duplicate lines.
Fixes #
> There is no associated issue with this fix/pull request.
> Clear up language and remove duplicate content

- appveyor.yml
Azure pipelines VMs does not have go 1.12 and using docker is very slow (12 min).
Appveyor VM images contain go 1.12 and the build takes 1:30min.
We can try out appveyor and see if it works for us.
> Trying out appveyor

- Makefile
Add `make help` to display documented `make` cmds.
```
$ make help
build                          build the athens proxy
build-ver                      build the athens proxy with version number
docs                           build the docs docker image
help                           display help page
run                            run the athens proxy with dev configs
test-unit-docker               run unit tests with docker
test-unit                      run unit tests with race detector and code coverage enabled
verify                         verify athens codebase
```
The help cmd is copied from Jess Frazelle's (jessfraz)
dotfile repo, see https://github.com/jessfraz/dotfiles/blob/master/Makefile#L68
**Mention …
> Makefile: Add `make help` to display documented cmds.

- cmd/proxy/actions/app_proxy.go
- cmd/proxy/actions/sumdb.go
- cmd/proxy/actions/sumdb_test.go
- config.dev.toml
- docs/content/configuration/_index.md
- docs/content/configuration/sumdb.md
- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
This PR adds two new configs: 
1. SumDBs (ATHENS_SUM_DBS)
2. NoSumPatterns (ATHENS_GONOSUM_PATTERNS)
Sum DBs such as sum.golang.org will be on by default.
This PR supports proxying requests to sum.golang.org by default (can be turned off via config). 
Furthermore, Athens can now take patterns that makes sure it never goes to the notary which will force the user to rebuild with a GONOSUMDB environment variable. 
Updates #1105
> actions: support proxying sum db urls

- pkg/storage/minio/cataloger.go
Minios's Cataloger impl. contains a call to `ListObjectsV2` but it provided the token on position 2 instead of 3 and so the token was never used.
> Minio Cataloger - fix List call - token should be on 3. position

- docs/content/configuration/_index.md
Fixed indentention in docs/content/configuration/_index.md so the page
is correctly generated by Hugo.
The documentation for the [configuration page](https://docs.gomods.io/configuration/) has a formatting issue:
Removed whitespace before the title.
Removed whitespace before the title.
> Fixes indentation in documentation

- cmd/proxy/actions/catalog.go
Fixed `/catalog` endpoint which didn't retrieve correctly `token `and `pagesize` parameters.
In order to correctly fetch `pagesize` and `token` parameters, I had replaced to `r.Query()` values instead of `mux.Vars()`.
Fixes #1236
> fix:  '/catalog' endpoint, which didn't allow fetch URL query parameters

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/values.yaml
- docs/content/_index.md
- docs/content/configuration/_index.md
- docs/content/configuration/upstream.md
- docs/content/install/install-on-kubernetes.md
Various docs don't mention public managed proxies like gocenter.io or proxy.golang.org
I added that :)
Fixes #1235
> Updating english docs to indicate the presence of hosted public proxies

- DEVELOPMENT.md
I found `git clone` missing in the command for checking out Athens code in `DEVELOPMENT.md`.
Just add it to the document.
> Add "git clone" to command for checking out the code in DEVELOPMENT.md

- .drone.yml
#1253 mentions that the `athens-proxy -version` returns `unset`
This is bc we are not setting the VERSION build-arg in our CI
http://plugins.drone.io/drone-plugins/drone-docker/ allows using build_arg
> Set build-args - VERSION

- cmd/proxy/Dockerfile
Fallowing the conversation in https://github.com/gomods/athens/issues/1227
It seems that `tini` is available on alpine.
This way we wouldn't need to adjust the Dockerfile for different archs (like ARM in case of #1227).
cc: @Kunde21
> Use alpine tini

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
Fixes a couple issues with the Helm chart regarding the netrc file.
* If only `netrc` is enabled but disk storage is disabled, previously the `volumeMounts` key of the deployment would not render causing the netrc mount to show up under the `ports` key.
* The documentation describes creating a Kubernetes secret with a key of `.netrc` but the chart was mounting the secret at `/etc/netrc/netrc` which is inconsistent with the docs.
> Fixes helm chart volumeMounts if only netrc is enabled

- docs/content/walkthrough.md
Since Docker 1.13 and greater includes `tini` we may get a warning that the athens-tini is not running as PID 1.
That's not a big problem, since the zombies are reaped by the docker-tini but it can be confusing.
I've added some docs explaining that.
Fixes #1268
> add docs explaining the tini warning

- pkg/storage/minio/checker.go
- pkg/storage/minio/lister.go
What is the problem I am trying to address?
Currently our storage.Exists implementation checks only for the mod file. This can be problematic if i.e. zip or info uploads failed.
How is the fix applied?
I'm checking if the len of objects equals 3 (zip, mod, info)
> minio : Use no. of objects for Exists check

- cmd/proxy/main.go
- config.dev.toml
- pkg/config/config.go
- pkg/config/config_test.go
This CL allows to activate `pprof` when needed to investigate any potential performances issues and / or proceed to profilings.
Introducing two new configuration params
allowing to activate pprof.
- `ATHENS_ACTIVATE_DEBUG_HANDLER`
- `ATHENS_DEBUG_HANDLER_PORT`
If `ATHENS_ACTIVATE_DEBUG_HANDLER` is set to `true` then `pprof` is started on the `ATHENS_DEBUG_HANDLER_PORT` port which is ideally different from the application port for security reasons as stated [here](https://mmcloughlin.com/posts/your-pprof-is-showing).
`pprof` won't be exposed by default.
Fixes #1177
> [debug] allow to expose pprof via config

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
Whenever you enable basic auth in an application, your kubernetes ready- and liveness-checks needs to be configured to use a username and a password. Currently, just setting the environment-variables does not seems like a good approach, because you can't access the variable values directly inside helm. 
This PR extracts basic-auth in a own configuration-entry instead of using the environment-variable based approach. When `basicAuth.enabled` is set to true, the respective environment variables will be filled with values from `basicAuth.user` and `basicAuth.password`. This is also the trigger to include basic-auth values into the HTTP-Headers for ready- and liveness-checks.
**Mention the issue number it fixes or add …
> [helm-chart] Basic-Auth support without environment-variables

- pkg/storage/s3/s3.go
Base URI is not required as it is not used anywhere in the code base and bucket names are provided.
Remove the unneeded code.
No issue
> [s3] base uri is not used anywhere remove it

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
- docs/content/install/install-on-kubernetes.md
In the current state of this helm-deployment there is no support for minio as storage-backend. Athens itself supports minio as storage backend, so the helm-chart should.
I added some more variables inside the values.yaml file and implemented them into the deployment-template like the other storage-types did. Also, i added a new section explaining how to use minio as backend inside the docs.
I did not find any issues regarding to this.
> [helm-chart] Adding support for minio as storage-backend

- go.mod
- pkg/download/upstream_lister.go
In 1.13, the Go command deduces a "module root" from an "import path" concurrently which means all paths are tried for `github.com/pkg/errors` such as `github.com/pkg/errors`, `github.com/pkg` and `github.com`. 
However, if the proxy returns a non 404/410 on any of the above calls, then the Go command will log to the user the returned error which could confuse the user thinking the `go get` command failed even though it didn't. 
For now, all attempts for `go mod` commands should return 404/410 until the mentioned issue in this PR gets resolved. Will follow up with another PR for .info/.mod/.zip
> pkg/download: return 404 on list/latest

- pkg/download/latest.go
- pkg/download/list.go
- pkg/download/version_info.go
- pkg/download/version_module.go
- pkg/download/version_zip.go
- pkg/errors/errors.go
- pkg/errors/errors_test.go
- pkg/module/go_get_fetcher.go
- pkg/module/go_get_fetcher_test.go
This is the `go mod download` side of this PR https://github.com/gomods/athens/pull/1299
Both gocenter.io and proxy.golang.org return 404/410 on incorrect module paths and incorrect versions. 
This PR does this and also makes sure the log level is Info
> pkg/module: return KindNotFound on incorrect mod download

- pkg/paths/path.go
To properly handle module version (branches) with capital letters. 
Added path decode for module version which caused issue for branches with capital letters. Used same function which is used to decode module names.
Fixes #1292
> Add mod version decoding to fix branches with capital letters

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/README.md
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
- docs/content/install/install-on-kubernetes.md
This commit adds support for gitconfig in the athens helm chart.
Reflects https://docs.gomods.io/configuration/authentication/#altassian-bitbucket-and-ssh-secured-git-vcs-s
We deploy athens to Kubernetes using helm chart, and we want it to be able to access our private repositories with modules.
This patch allows injecting any custom git config to the athens container. This is kind of similar to netrc support, but in our case gitconfig support would provide more flexible configuration options.
> Add gitconfig support for helm chart

- pkg/storage/mongo/getter.go
In the mongo/getter implementation there is duplicated code in the Info and GoMod functions. The purpose of this PR is to reduce the duplicated code without any changes to the operation of either of the functions. 
There was also a difference between how the Info and GoMod functions passed the reference for the query result to the Decode function. The Info passed a pointer to the reference while the GoMod function just passed the reference. Mongo handles both so there was no error during run time but this refactor ensures that Info and GoMod call the mongo.Decode function the same way.
The common/duplicated code from Info and GoMod functions has been moved into a new getter.Query function.
**Mention the issue …
> Updates to mongo getter to reduce duplicate code

- pkg/storage/minio/minio.go
- pkg/storage/minio/minio_test.go
The incorrect error was being bubbled up when using an "_" in the in Minio bucket name.  It was returning the BucketExists error which uses a less strict form of error checking.
The fix simply ignores the BucketExists error (the execution path is already inside an error condition) when there is an error.  If the bucket does exist, it correctly returns a storage backend.   I added test cases locally to minio_test.go since they are specific to minio and not the overall compliance tests.  Let me know if this isn't ok but I felt it made more sense.
Fixes #1295
> Fixed Minio NewStorage to return the correct error

- pkg/storage/s3/s3.go
SigSegV in Endpoint creds
Found out that the AWS HTTP Client was null
Start by using default aws config to create http client automatically
Fixes #1283
> Fixes endpoint creds

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
The helm chart failed to deploy Athens properly when basic auth is turned on
I removed the double-quote from the params
Fixes #1303
cc/ @qiuyuzhou
> Fixing basic auth vars in the helm chart

- pkg/storage/mongo/mongo.go
- pkg/storage/mongo/mongo_test.go
When creating a new Mongo client, athens doesn't check for error messages returned when setting the database URL. This change checks for errors returned by the mongo ApplyURI function and wraps/returns the errors. 
In the newClient function, the options.Validate is called after the options.ApplyURI function to check that that the supplied URI value didn't trigger an error with the mongo library. Also, the function signature for newClient was altered to remove the parameter since it is no longer used. 
Fixes #1328
> Add check for mongo configuration errors.

- pkg/config/config.go
- pkg/config/config_test.go
using a host enables the ability to bind to a specific interface
> add support for a host in ensurePortFormat

- docs/content/configuration/storage.md
- pkg/config/config_test.go
- pkg/config/mongo.go
- pkg/storage/mongo/mongo.go
- pkg/storage/mongo/mongo_test.go
The mongo database's initialization code uses hardcoded values for the database and collection names. An environment variable for the database name exists as ATHENS_MONGO_DEFAULT_DATABASE but is not used during the mongo initialization. There is no existing environment variable for the collection name. 
Mongo will use the values set in the mongo storage configuration or will default to "athens" or "modules" during initialization. The environment variable, ATHENS_MONGO_DEFAULT_COLLECTION, is added to set the name of the collection. This will default to "modules" if not set. The value stored in the existing environment variable ATHENS_MONGO_DEFAULT_DATABASE is now used to set the mongo database name or will revert …
> Fix Mongo initialization to use environment variables for db/coll names

- pkg/storage/mongo/mongo_test.go
I am adding tests around the mongo query function. The query function contains common code that is used by both the Info and GoMod functions in getter.go. 
I created two integration tests in mongo_test.go that test the function when there are modules in the database and when modules cannot be found. These tests are very similar to the existing tests in compliance.go that are used to test the Info and GoMod functions that in turn call query(). 
I am having trouble triggering unexpected type errors from within the mongo driver reliably. I would like to add tests for a non 'nil' queryResult error and KindUnexpected if possible (see snippet below).  
```
if queryErr := queryResult.Err(); queryErr != nil {
return nil, …
```
> Write tests for the new Mongo query function

- config.dev.toml
- docs/content/configuration/storage.md
- pkg/config/s3.go
- pkg/storage/s3/s3.go
Add relative URI for AWS fargate.
Give a different config for users to append container URI
> Add relative URI for AWS fargate.

- scripts/check_gofmt.sh
We don't have a vendor directory anymore :smile: :tada:
We have code in `./scripts/check_gofmt.sh` that ignores go code in the `vendor/` directory, but we don't have a `vendor` directory anymore
I removed the check
> Removing gofmt vendor ignores

- pkg/download/mode/mode.go
- pkg/download/mode/mode_test.go
Right now `mode.NewFile()` returns an HTTP 400 error when `Config.DownloadMode` is not set. This doesn't make a lot of sense, because the consumer of the error is not an HTTP client, but an administrator attempting to configure Athens for the first time. 
`mode.NewFile()` no longer returns HTTP errors, and instead returns either `mode.ErrDownloadMode` or a formatted error stating that the specified `DownloadMode` is not valid. This also adds some basic testing to ensure the function returns expected error values.
Refs #1336
> Don't return an http error when a DownloadMode is invalid

- .drone.yml
- cmd/proxy/Dockerfile
Now that Go 1.13 is out, let's use it.
> Upgrade to Go 1.13

- cmd/proxy/actions/sumdb.go
- cmd/proxy/actions/sumdb_test.go
This makes it so that if a user enters `github.com/company/*`, it will match against all modules and submodules of github.com/company such as `github.com/company/private` and `github.com/company/private/other` 
fixes https://github.com/gomods/athens/issues/1386
> proxy/actions/sumdb: copy Go behavior for pattern matching

- cmd/proxy/actions/sumdb.go
- pkg/download/mode/mode.go
- pkg/download/mode/mode_test.go
- pkg/paths/path.go
- pkg/paths/path_test.go
This will match the behavior of GOPRIVATE/GONOPROXY/GONOSUMDB
This addresses an issue with download directives where subpackages do not match if there are any additional `/` characters (counter to how GOPRIVATE/GONOPROXY/GONOSUMDB all work)
Matched the behavior used by `go mod`. Shared the new matching code with SumDB matcher as well.
Fixes #1408
> Use glob matching for package paths (Fix #1408)

- docs/content/configuration/storage.md
For #1410 - updated docs to add instructions for configuring Athens to use the Azure Blob storage provider
> Added storage configuration section for Azure Blob Storage

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/service.yaml
- charts/athens-proxy/values.yaml
It is often use to add custom annotations to a Service deployed
through Helm, so this PR adds the ability for a user to specify
annotations in their values file. For such use case we have seen
is when working in conjunction with external-dns, we want to assign
DNS properties of the Service, but currently cannot because this
Helm chart does not support it.
We are trying to apply custom annotations to the Athens k8s Service to make it work with our usage of external-dns.
I implemented a pattern seen in several other helm charts.
(See above)
> Add ability to annotate the proxy Service via Helm

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/values.yaml
Fix an import bug: https://github.com/gomods/athens/issues/1390
Signed-off-by: jtcheng <jtcheng0616@gmail.com>
There is an import bug  in v0.6.0 as description as https://github.com/gomods/athens/releases/tag/v0.6.1.
Change the default tag from v0.6.0 to 0.6.1
Fixes #1390
**Confusion**
I dont know how to publish chart to `https://athens.blob.core.windows.net/charts`.
Do I need to deploy it  by hand ?
> Update tag of gomods/athens in chart

- pkg/module/prepare_env.go
For some arcane reasons go can't download private module if there is blank `GIT_SSH=` in environment.
I've tried to alter the way we construct the environment variables in `prepareEnv` so we don't set variables that are not present.
I've introduced the ` os.LookupEnv(key)` call, and started to append variables only if boolean is true and variable is present.
Fixes #1398
> pkg/module: set only present environment variables

- .dockerignore
While playing around locally with the athens project, I realize pretty much the entire folder is being included in the docker build context of images.
I have updated the .dockerignore file.
No existing issue to reference.
I have simply added `**/.git` to the .dockerignore file.
This brings the size of the docker build context from ~71MB down to ~16mb
> Add .git to .dockerignore, bringing docker build context from 71MB to 16MB

- .drone.yml
It looks like drone is taking longer to pull the image down for athens, checking if 10 seconds will be okay. However, we can probably write a small bash script to go in a loop and wait until the server is ready.
> drone: give more time for athens to boot up

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
Apparently Athens brakes with long k8s cluster upgrade (downtime is longer as default thresholds with livenessprobs)
Make livenessProbs thresholds configurable so we can extend health check times
No issue
> Added configurations for k8s livenessProbs thresholds

- cmd/proxy/Dockerfile
For repositories that store files in git-lfs, the checksum will
differ for clients with and without git-lfs. Clients without git-lfs
will use the [git-lfs pointer](https://github.com/git-lfs/git-lfs/blob/master/docs/spec.md#the-pointer) for calculation, clients with will use
the real files.
git-lfs is installed with the other utilities in the `cmd/proxy/Dockerfile`.
Fixes #1448
> Install git-lfs on proxy container

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
The chart creates a yaml that has duplicate keys. One key will be ignored by Kubernetes.
Renamed the annotations to distinct names.
The yaml becomes valid.
> Renamed redeploy annotations to fix duplicate key in yaml

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
- cmd/proxy/actions/basicauth.go
- cmd/proxy/actions/basicauth_test.go
Currently, the Helm chart requires the HTTP basic authentication credentials (if any) to be defined  in the `values.yaml` file or via the CLI. Both of these approaches are cumbersome when working with [Flux](https://fluxcd.io/) and the [Helm operator](https://github.com/fluxcd/helm-operator), as that would require these credentials to be checked (as plain text) into source control. This PR updates the Helm chart in order to make it possible to reference a secret instead. This secret can then be managed using [Sealed Secrets](https://github.com/bitnami-labs/sealed-secrets) or bby some other process. 
* Replace `basicAuth.username` and `basicAuth.password` with `basicAuth.secretName`, `basicAuth.usernameSecretKey` …
> Read basic auth credentials from a secret.

- .drone.yml
- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- config.dev.toml
- pkg/config/gcp.go
- pkg/stash/with_gcs_test.go
- pkg/storage/gcp/gcp.go
- pkg/storage/gcp/gcp_test.go
When I merged https://github.com/gomods/athens/pull/1428,
I accidentally introduced a build failure where Athens couldn't find the GCS key,
and wouldn't start up. It silently failed though, because we start Athens up in
the background
I have added backward compatibility to Athens, so that it falls back to the old
`ATHENS_STORAGE_GCP_SERVICE_ACCOUNT` env var if the new `ATHENS_STORAGE_GCP_SERVICE_ACCOUNT`
isn't found
Closes #1479
Fixes https://github.com/gomods/athens/issues/1478
In a follow up to this PR, the `.drone.yml` needs to be updated so that the `athens-proxy` step uses the `gomods/athens:canary` …
> Fixing the build failures from a missing GCS Key

- .drone.yml
In #1480, we had to temporarily use a commit-specific athens image
to fix the build at the time. In that PR, we wrote a TODO to change
it back.
I've changed the image we use in drone back to `canary`
This is a follow-up to the follow-on work described in 
https://github.com/gomods/athens/pull/1480#issue-349109197
> Going back to using the canary image in drone

- config.dev.toml
- docs/content/configuration/storage.md
- pkg/config/s3.go
- pkg/storage/s3/s3.go
This is required to support hosted S3-compatible storages (e.g. OpenStack).
I've added `Endpoint` config field with `AWS_ENDPOINT` env and started passing it (if not blank) to `awsConfig.Endpoint`.
From aws-sdk-go docs:
```go
// An optional endpoint URL (hostname only or fully qualified URI)
// that overrides the default generated endpoint for a client. Set this
// to `""` to use the default generated endpoint.
//
// Note: You must still provide a `Region` value when specifying an
// endpoint for a client.
Endpoint *string
```
https://github.com/aws/aws-sdk-go/blob/98babde4e50a39648e6618b79d256074f451754d/aws/config.go#L44-L50
> storage/s3: support custom endpoint url

- Makefile
`make build` runs `cd cmd/proxy` before doing the `go build`. That means that you end up in a different directory after you run this command.
I've changed the `make build` from `cd cmd/proxy && go build` to `go build -o ./cmd/proxy/proxy ./cmd/proxy`, so that the exact same thing happens as before, except you stay in the directory you started at 
Fixes https://github.com/gomods/athens/issues/1495
> Making 'make build' not cd into the cmd/proxy directory

- pkg/stash/stasher.go
This helps users debugging athens know that something was not found in storage
> stasher: log when a stash event occurs

- docs/content/configuration/filter.md
The filter docs (now deprecated) had a broken link to the download mode documentation
I fixed the link
N/A
> Fixing the link to the download config docs from the deprecated filter docs

- cmd/proxy/Dockerfile
Fixes https://github.com/gomods/athens/issues/1529
I believe will require a new patch release
> Dockerfile: ensure right perms for production setting

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/values.yaml
The [latest release](https://github.com/gomods/athens/releases/tag/v0.8.0) helm chart is pointing to an old image version, v0.7.0
I updated the image version to v0.8.0
Fixes #
> Updating helm chart image version to latest

- README.md
The "Code like the go team" link to the printed version goes to a broken link
I fixed the link. It points to https://www.brianketelsen.com/slides/gcru18-best/#1 now.
Fixes https://github.com/gomods/athens/issues/1565
> Fixing code like the go team printed version link

- config.dev.toml
I goofed in #1545, this fixes that goof
Moved the Password field for `SingleFlight.Redis` back to where it was in the example config
> Move SingleFlight.Redis.Password back under SingleFlight.Redis in config

- cmd/proxy/actions/storage.go
- config.dev.toml
- docs/content/configuration/storage.md
- go.sum
- pkg/config/config.go
- pkg/config/external.go
- pkg/config/storage.go
- pkg/storage/compliance/tests.go
- pkg/storage/external/client.go
- pkg/storage/external/external_test.go
- pkg/storage/external/server.go
- pkg/storage/fs/fs.go
- pkg/storage/fs/fs_test.go
This PR adds an http external storage implementation. It re-uses a lot of what we have already and optimizes "save" operations by uploading all 3 files (info/mod/zip) in one endpoint as a piped multi-writer. 
Basic documentation and example is included, but I'll add more docs in follow ups. 
Fixes https://github.com/gomods/athens/issues/1110
Fixes #1353
Fixes #1130
Fixes #1131
Closes #1551
> pkg/storage: add External implementation

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/values.yaml
I just did the v0.8.1 release and the helm chart is outdated, it still points to the v0.8.0 docker image tag.
I've updated the values.yaml and the Chart.yaml files according to [these documentation](https://github.com/gomods/athens/blob/master/DEVELOPMENT.md#finishing-up)
N/A
> Updating the helm chart for release v0.8.1

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/deployment.yaml
- charts/athens-proxy/values.yaml
If [`storage.disk.persistence.enabled`](https://github.com/gomods/athens/blob/6b5b62c0fceb97e8c86816fcf82a93f730a330e3/charts/athens-proxy/values.yaml#L49) is set to `true` and the `accessMode` is not `ReadWriteMany`. the default strategy must be switched to `type: Recreate`. if not it will fail as the other pod is using the PVC.
> charts: allow to set deployment update strategy

- cmd/proxy/Dockerfile
In the recent change we added a build argument for the alpine version:
https://github.com/gomods/athens/blob/a8467661c219d5c31733ec1fc2ebb8fed1fb489a/cmd/proxy/Dockerfile#L19-L20
Due to it being a multistage build the argument is dropped before `FROM` so we need to set this globally.
You can see the issue manifested here https://cloud.drone.io/gomods/athens/1763/1/10
Unfortunatly this wasn't picked up during PR due to docker-build-latest only being called when branch is master and on push.
Edit to reference issue #1584
> fix build argument issue in drone deployment

- docs/content/configuration/download.md
Fixed a missing `:` when configuring `custom:$BASE_64`.
Change the docs.
Signed-off-by: Bradley Wilson-Hunt <bwilsonhunt@gmail.com>
> docs: typo for ATHENS_DOWNLOAD_MODE custom

- DEVELOPMENT.md
- We needed a reminder to update the Docker image version when doing a helm release
- The link provided in the release steps to find changes between the newest release is also inaccurate
- There's now a step in the helm release procedure
- The link in the release notes section was clarified
> Update the release steps with a few details

- cmd/proxy/actions/app_proxy.go
- cmd/proxy/actions/app_proxy_test.go
Fixes: #1619
http.StripPrefix will look at the entire request path when called,
if we do not include config.PathPrefix then the StripPrefix call
will never receive a valid path from the application and the user
will always get a 404 error.
There were no test where I could easily check this regression so
I also added a few endpoint tests, the last test will fail with
a 404 instead of 403 if this change in not applied.
Fixes #
> Fix sumdb/* paths when config.PathPrefix is set

- cmd/proxy/actions/app.go
- cmd/proxy/actions/storage.go
This PR adds the ochttp Transport plugin into an http client in order to propagate tracing. 
Fixes https://github.com/gomods/athens/issues/1625
> Add client tracing to external storage requests

- cmd/proxy/actions/app.go
- pkg/middleware/middleware_test.go
- pkg/middleware/validation.go
I noticed that our ValidationHook does not trace outgoing client calls. This PR does two things: 
1. It adds client tracing to outgoing Validation calls
2. It propagates the request context so that if a request is cancelled, the ValidationHook also gets cancelled
> pkg/middleware: add tracing to ValidationHook

- cmd/proxy/actions/app_proxy.go
- config.dev.toml
- pkg/config/config.go
- pkg/download/protocol_test.go
- pkg/module/go_get_fetcher.go
- pkg/module/go_get_fetcher_test.go
This PR adds a new "GoGetDir" config that users can specify to be passed to the module.Fetcher to leverage K8s volumes as well as have a consistent place for where "go mod download" results are temporarily stored. 
Fixes https://github.com/gomods/athens/issues/1635
> Allow users to specify the module fetcher's temporary directory

- pkg/download/handler.go
- pkg/download/handler_test.go
- pkg/download/mode/mode_test.go
If a downloadURL with a path such https://internal.domain/repository/gonexus is configured then this is truncated to https://internal.domain when redirecting to the upstream proxy, resulting in failures.
In getRedirectURL append the path to the downloadURL path rather than replacing it.
Fixes #1639   
Signed-off-by: Keith Burdis <keith.burdis@gs.com>
> Support downloadURLs with paths

- docs/content/configuration/upstream.md
Broken link in documentation. Basically, same as #1524, just for another page.
I fixed the link.
None.
> Fix link in deprecation note.

- docs/content/design/proxy.md
The documentation at https://docs.gomods.io/design/proxy/#catalog-endpoint incorrectly gives the query parameter "format" instead of "pagesize".
Updated the markdown.
none
> Replace limit with pagesize in docs for catalog endpoint

- pkg/index/compliance/compliance.go
- pkg/index/mem/mem.go
- pkg/index/mysql/mysql.go
- pkg/index/postgres/postgres.go
- pkg/stash/stasher.go
If a Stasher calls Index on a backend, and that backend already has the given module@version, then the backend could (and should) return a DuplicateEntry error kind. 
If that happens, we should gracefully handle and ignore this error because we know our index already has this module@version. 
This scenario happens when a user switches backend storages but has not switched index storages. 
Updates https://github.com/gomods/athens/issues/1546
> index: gracefully handle duplicate module indexes

- cmd/proxy/actions/index.go
- cmd/proxy/actions/index_test.go
Following up on the previous /index addition to Athens, this PR adds unit tests to the /index http handler. 
It also adds better logging and error handling to the handler itself.
> actions: add index handler tests

- pkg/stash/with_redis_test.go
I noticed that the Redis test is failing due to some spacing issues in the error message. 
String matching when it comes to error handling is usually not great, but Redis doesn't provide us with error codes here so we should make the string matching a bit looser as there is no compatibility guarantee.
> pkg/stash: fix redis failing test

- go.mod
- go.sum
- pkg/config/config_test.go
This PR updates our go-cmp dependency to the latest version and also utilities the `Diff` functionality to output better test failures when the config is not what we expect them to be. 
Before: 
```
=== RUN   TestDefaultConfigMatchesConfigFile
TestDefaultConfigMatchesConfigFile: /Users/marwansulaiman/marwan/athens/pkg/config/config_test.go:488: Default values from the config file: &{{300} development go direct [GOPROXY=direct] 10  30 debug none false :3001  http://localhost:14268  prometheus memory http://localhost:3001 :3000   false        [https://sum.golang.org] [] sync  memory robots.txt none 0xc00046cea0 0xc000451940 0xc00047a8f0} should equal to the default values returned in case the config file isn't provided &{{300} development go proxy.golang.org [GOPROXY=direct] 10  30 debug …
```
> pkg/config: make test failures output diff instead of %+v

- cmd/proxy/actions/app.go
- pkg/middleware/log_entry.go
- pkg/middleware/log_entry_test.go
- pkg/middleware/requestid.go
- pkg/middleware/requestid_test.go
- pkg/requestid/requestid.go
This PR adds a new `Athens-Request-ID` header that if present would propagate throughout logs and requests. And if not present, a new request id will be created. 
Fixes https://github.com/gomods/athens/issues/1654
> pkg/requestid: add Request ID to Athens requests and logs

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/ingress.yaml
`extensions/v1beta1` API for Ingress is deprecated since Kuberentes 1.14.
Ref: https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG/CHANGELOG-1.14.md#deprecations
This commit adds a check using Helm Capabilities to deploy Ingress with newer API.
> Use new Ingress API

- docs/content/install/using-docker.md
A broken link to the docker hub image in the documentation.
Link fixed!
> Fix broken link to docker hub

- pkg/storage/s3/s3.go
Support IAM Roles for Service Accounts, when the back-end storage is an S3 bucket.
If AWS credentials are provided keep using then, otherwise use default credential methods.
I have installed a pod on a kubernetes cluster with a docker image that has this fix and athens proxy with s3 bucket as back-end storage. The cluster was configured with a service account with appropriate IAM roles. Athens proxy seems to work fine with this change.
> Support IRSA for S3 bucket

- .github/workflows/codeql.yml
- .github/workflows/security.yml
CodeQL's GitHub integration is out of invite only and now available to public repositories. We should have some security scanning in place as a check.
Added the CodeQL action which autobuilds, scans and reports issues. It currently runs against main and on a schedule of 0 15 * * 0 or 15:00 every Sunday.
> Implement CodeQL GitHub Action

- pkg/download/addons/with_pool.go
- pkg/download/addons/with_pool_test.go
- pkg/download/handler.go
- pkg/download/handler_test.go
- pkg/download/protocol.go
- pkg/download/version_zip.go
- pkg/storage/azureblob/azureblob.go
- pkg/storage/azureblob/getter.go
- pkg/storage/compliance/tests.go
- pkg/storage/external/client.go
- pkg/storage/external/server.go
- pkg/storage/fs/getter.go
- pkg/storage/gcp/getter.go
- pkg/storage/getter.go
- pkg/storage/minio/getter.go
- pkg/storage/module.go
- pkg/storage/mongo/getter.go
- pkg/storage/s3/getter.go
This PR enables Athens to return an accurate byte count of a module@version's size via the Content-Length header. 
It also allows HEAD requests to get said header without returning the content of the zip file. 
This is needed for Athens to integrate with pkgsite, particularly here: https://github.com/golang/pkgsite/blob/fd89b15b08609658e2b6d1363f52fd2f691db311/internal/proxy/client.go#L97:L116
> Add Content-Length to .zip requests

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/service-account.yaml
- charts/athens-proxy/values.yaml
Right now, there is no way to use existing service accounts to deploy athens using helm chart. It always tries to create a new one. But the requirement here is to use a service account that has already been created.
Tested with dry-run and on kubernetes cluster. With this change, athens can use an exiting service account.
Fixes #
> Allow using existing service accounts

- docs/content/install/install-on-aws-ecs-fargate.md
Documentation on some of the common questions/gotchas when deploying Athens in AWS, more specifically on ECS Fargate. Although the core principles apply to other AWS deployment architectures.
Wrote some documentation. Definitely inspired by #1694 & #1703 as I ran into similar issues.
Fixes #1703
Fixes #1694 
Contributes to #1350 ?
I'm also willing to contribute fully toward #1350 as #1543 since I have the code in use already. Happy to change/fix anything as well.
> docs: AWS Fargate (ECS) details

- config.dev.toml
I am suggesting replacing a vague phrasing about how GCP out-of-box authentication works. If Athens is used in a GCP product like Cloud Run it will work without any extra work because `GOOGLE_APPLICATION_CREDENTIALS` variable is automatically propagated by GCP so the previous comment was not wrong but this is more helpful for custom deployments where `GOOGLE_APPLICATION_CREDENTIALS` approach can also be used.
A comment in the config file.
> Update GCP Storage authentication comment

- pkg/download/version_zip.go
- pkg/storage/s3/getter.go
In some cases, Amazon S3 may not always return a Content-Length header. In this case, the size will not be set and take the zero value, and `http.ResponseWriter` will complain:
```
http: wrote more than the declared Content-Length
```
The data will be ignored
Skip  `Content-Length` in response when the size is 0, so at least the data can be sent.
> Use actual content length when it is not available in headers

- cmd/proxy/Dockerfile
Alpine 3.11 which the athens images is built on will reach end of support soon.
Use a recent version of alpine.
None
> Update alpine version to 3.14.2

- pkg/storage/s3/s3.go
Fixing a panic when S3 storage is used but configured without default storage
Per @kylelemons 's suggestion, I've changed the initial s3 config to use AWS defaults
NOTE: I'm not very familiar with S3 storage in Athens, so it would be very helpful if someone more knowledgeable than me could review this
Fixes #1729
> Fixing panic with S3 storage

- cmd/proxy/Dockerfile
- docs/content/configuration/authentication.md
Athens does not build on main. See example build:
https://cloud.drone.io/gomods/athens/2273/1/10
Alpine moved bzr to unmaintained status. See
https://gitlab.alpinelinux.org/alpine/abuild/-/issues/10000
Deprecate bzr from the Dockerfile as it is deprecated from alpine.
Also, update alpine version.
> Deprecate bzr as it is unmaintained.

- Makefile
- pkg/stash/with_etcd.go
- scripts/check_golint.sh
- scripts/check_govet.sh
As mentioned in #1743 the Go modules environment flag is set to `off`
in the script which appears to cause a warning message for each module
of the codebase that it is "not in GOROOT".
Set to `auto` as this allows the same build to be run the original way
should someone choose to delete the `go.mod` file from the project root.
Golint warning for each submodule of Athens "package not in GOROOT" when running Make target `verify`
Set `GO111MODULE=auto` in `./scripts/check_golint.sh` 
Fixes #1743
> Set GO111MODULE to auto in golint script– #1743

- docs/content/configuration/prefill-disk-cache.md
Making the process of filling Athens disk storage (if it is run cut off from the internet) more easy and fast
Use docker-compose file as described in the docs do download go modules
None
> a new way to pre-fill disk storage

- .drone.yml
- docker-compose.yml
- go.mod
- go.sum
- pkg/stash/with_redis_sentinel_test.go
Redis tests have flakes, this leads to a bad CI.
Redis tests have flakes, by using depends_on flag; I am trying to reduce these flakes.
I tested by force-pushing multiple commits.
Fixes #
> fix flake on redis-sentinel by depending on redis container / step.

- pkg/stash/with_redis_sentinel_test.go
Revert retries as main is failing again. There is no point in
slowing down the flaky tests.
Reverting the previous test
Fixes #
> Revert retries in redis-flake as builds are failing again.

- charts/athens-proxy/Chart.yaml
- charts/athens-proxy/templates/ingress.yaml
- charts/athens-proxy/values.yaml
update helm chart ingress to add apiVersion `networking.k8s.io/v1` in order to work with k8s 1.22+
Fixes #1761
> chore(chart): update ingress to support apiVersion networking.k8s.io/v1

- pkg/storage/minio/getter.go
When using the Minio storage provider, there is an apparent memory or goroutine leak, causing memory usage to steadily increase in use. After profiling, it appears that it is related to `GetObject` calls on the `minioClient`. I noticed that the `minio.Object` that is returned has a `Close` method, and found [a similar issue in minio/warp](https://github.com/minio/warp/issues/113) that was [fixed by closing the objects](https://github.com/minio/warp/pull/115/files).
This PR adds deferred `Close` calls in the `storageImpl.Info` and `storageImpl.GoMod` functions so that the objects may be released and garbage collected. The `storageImpl.Zip` function does not use `defer`, since it has the object embedded into the return value, so I added the `Close` only on error.
> Resolve memory leaks when using Minio storage

- .goreleaser.yml
I would like to add builds for x86_64 machines to the goreleaser versions.
Simple addition to the .goreleaser.yml config file
None, this is a tiny PR to make my request easier to accept.
> build releases for x86_64

- go.mod
The direct and indirect deps in go.mod are mixed in two `require` blocks
Separate direct and indirect deps, which is the default behavior of Go 1.18
> regrouping go.mod

- cmd/proxy/actions/storage.go
Athens doesn't emit metrics when it calls to S3
Athens already has an HTTP client created from go.opencensus.io/plugin/ochttp, which can "that instruments all outgoing requests with OpenCensus stats and tracing". So we can pass that to S3 client.
> Passing http client to S3 client

- pkg/download/protocol.go
We started receiving some `RequestCanceled: request context canceled` errors after setting the download mode to `async_redirect` (same problem happens with `async` as well).
After some investigation we found that the same context from the HTTP handler [is being passed to stasher](https://github.com/gomods/athens/blob/main/pkg/download/protocol.go#L264) and the async routines fail to continue after the request is complete since the context gets cancelled after completion.
This PR creates a new context with custom timeout and copies over some values from the old context to solve this issue.
> copy context before starting stash operations to prevent ctx cancellations

- pkg/storage/s3/s3.go
Using default S3 credentials is currently broken in the main branch, and based on my investigation it broke after this change: https://github.com/gomods/athens/issues/1730.
Using `defaults.Config()` [sets `Credentials` as anonymous]( https://github.com/aws/aws-sdk-go/blob/v1.40.31/aws/defaults/defaults.go#L57) and hence it [breaks aws lib's logic to resolve default credentials](https://github.com/aws/aws-sdk-go/blob/v1.32.7/aws/session/session.go#L575) which only works when `Credentials` passed by the user to [`session.NewSession` ](https://github.com/gomods/athens/blob/main/pkg/storage/s3/s3.go#L68) is `nil` and hence it ends up using the anonymous credential leading to authorization failures.
Note:
- Before https://github.com/gomods/athens/issues/1730 `config.Credentials` was being set …
> fix s3 credentials set to anonymous by default

- pkg/observ/stats.go
HTTP client metrics are still not collected after #1786
Registering HTTP client views in additional to the server views. Also `ochttp.DefaultServerViews` is [deprecated](https://pkg.go.dev/go.opencensus.io/plugin/ochttp@v0.23.0#DefaultServerViews). The official doc recommends registering server views individually, which I did.
Partially Fixes #446
> Register HTTP client views for stats

- pkg/storage/s3/checker.go
Athens using AWS S3 as storage could return 404 back to users even if the requested module is present in S3 as the page contents could be truncated (max 1000 objects). 
See details here https://github.com/gomods/athens/issues/1801
Iterate through all S3 pages for the S3 prefix input using https://docs.aws.amazon.com/sdk-for-go/api/service/s3/#S3.ListObjectsPagesWithContext
Fixes https://github.com/gomods/athens/issues/1801
> Update s3 checker to iterate through all objects pages

- pkg/download/protocol_test.go
- pkg/storage/rev_info.go
All recent CI jobs of Athens are failing.
Go 1.9 added a new `Origin` field to the [RevInfo](https://pkg.go.dev/cmd/go/internal/modfetch@go1.19#RevInfo) struct. When a test tries to decode the .info file downloaded by go mod, the addition field cause the decoder to fail, because the decoder `DisallowUnknownFields()`. Copying adding the new fields introduced in Go 1.19 fixes the issue.
The changes in this PR is taken from #1799.
This would fix the failing test in #1793
> Adding new fields to RevInfo

- cmd/proxy/main.go
- config.dev.toml
- pkg/config/config.go
- pkg/config/config_test.go
Currently, when shutting down the server (via `SIGINT`), the shutdown closes any open connections after only 10 seconds (via a `context.WithTimeout`). This does not provie a lot of time for longer operations, such as listing versions, or downloading a larger module zip file.
When running in Kubernetes, and scaling instances or changing config, this causes a lot of dropped connections and gateway errors. 10 seconds is arguably much too short, and should be configurable.
This commit increases that default to 60 seconds, and adds a config variable to allow users to specify their desired timeout.
> Make shutdown timeout configurable

- cmd/proxy/main.go
- internal/shutdown/signals.go
- internal/shutdown/signals_notunix.go
When running Athens on a unix-like OS (linux, darwin, etc), the TERM signal is not being handled to perform a graceful shutdown, only `INT`. This is especially problematic on Kubernetes, where the default signal sent to pods is `TERM`.
This commit adds a new package to get the appropriate signals based on the operating system, using `go:build` tags. For `unix`, it includes `os.Interrupt` AND `syscall.SIGTERM`, but only `os.Interrupt` for others, which may not support that signal.
> Handle SIGTERM on unix-like OS

- cmd/proxy/actions/app_proxy_test.go
- cmd/proxy/actions/auth.go
- e2etests/all_test.go
- pkg/config/config_test.go
- pkg/download/list_merge_test.go
- pkg/download/mode/mode.go
- pkg/download/protocol_test.go
- pkg/middleware/middleware_test.go
- pkg/middleware/validation.go
- pkg/module/filter_test.go
- pkg/module/go_get_fetcher_test.go
- pkg/stash/stasher_test.go
- pkg/stash/with_gcs_test.go
- pkg/storage/azureblob/getter.go
- pkg/storage/compliance/benchmarks.go
- pkg/storage/compliance/tests.go
- pkg/storage/external/client.go
- pkg/storage/external/server.go
- pkg/storage/gcp/getter.go
- pkg/storage/minio/getter.go
- pkg/storage/mongo/mongo.go
- pkg/storage/mongo/mongo_test.go
- pkg/storage/s3/getter.go
`io/ioutil` package was deprecated in Go 1.16 and should not longer be used.
Replaces all occurrences of `io/ioutil` with functions on the `io` or `os` package.
The replacement functions can be found in the package docs for [`io/ioutil`](https://pkg.go.dev/io/ioutil) for reference.
> feat: replace ioutil with io and os

- cmd/proxy/actions/app_proxy.go
- pkg/stash/with_redis.go
- pkg/stash/with_redis_sentinel.go
- pkg/stash/with_redis_sentinel_test.go
- pkg/stash/with_redis_test.go
The Redis package used by `pkg/stash/with_redis*` occasionally logs bits of information, such as when a Redis Sentinel is discovered or changes, but it uses its own logger by default. If Athens is configured to log in JSON but Redis is logging in plain text, this creates problems when parsing the log output.
Make an adapter struct around `pkg/log.Logger` to implement the interface that Redis v8 expects, then pass the logger to the `WithRedis*` functions to call `redis.SetLogger`.
Haven't found an Issue specifically for this.
> Pass Athens's logger to the Redis package

- pkg/config/config_test.go
Ensure no leftover environment variables between tests in `pkg/config/config_test.go`.
Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.
Reference: https://pkg.go.dev/testing#T.Setenv
```go
func TestFoo(t *testing.T) {
// before
oldVal := os.Getenv("key")
defer os.Setenv("key", oldVal)
os.Setenv(key, "new value")
// after
t.Setenv(key, "new value")
}
```
> test(pkg/config): use `t.Setenv` to set env vars

- .github/workflows/ci.yml
- DEVELOPMENT.md
- README.md
- pkg/stash/with_azureblob_test.go
- pkg/storage/azureblob/azureblob_test.go
- pkg/storage/gcp/gcp_test.go
This PR removes the last references to Drone.
* Env vars now use a Github Actions PR Number Env var
* `athens_drone_stash_bucket` was left as this is a bucket name, and it is unclear if changing it will break things.
* The build status badge has been updated to Github Actions
* References in documentation have been fixed
Fixes #1833
> chore: remove last drone remains

- cmd/proxy/Dockerfile
- docs/content/install/using-docker.md
In many modern deployment environments, root containers are not allowed. While it is simple to switch the user on the fly, that user needs to have a home directory for this to work.
A non-root user `athens` uid/gid 1000 is created in the docker image, but not used by default. As existing users will still want to use `root` for this to be non-breaking, the new user is not used by default. Documentation on the non-root user has also been added to make this change discoverable.
> feat: add non-root user to docker image

- pkg/storage/s3/checker.go
- pkg/storage/s3/getter.go
Using `errors.AsErr` as suggested by @nrwiersma , so we don't need to import two errors packages.
> Refactoring: Use errors.AsErr

- .github/workflows/ci.yml
All the WFs are running twice. See https://github.com/gomods/athens/pull/1850 for example. This fixes it.
pull_request takes in account for any activity
> Remove duplicate runs of all the workflows

- .github/workflows/ci.yml
The CI linter is currently uses docker, which is very slow due to not having a cache.
Use the provided Golanci-lint actions package which has caching builtin.
> chore: use builtin action linter package

- Makefile
- cmd/proxy/Dockerfile
This PR updates alpine to 3.17 and builds smaller athens binary. By using these flags; we are saving around 14M in athens binary size.
> Update alpine to 3.17 and build smaller binary.

- .github/dependabot.yml
Github actions, like go modules, should be kept up-to-date.
Instruct dependabot to check github actions.
> chore: keep github actions up-to-date

- pkg/config/config.go
- pkg/config/config_test.go
This relaxes the permissible config file permission to allow read for group and other (effectively 0o644).
For reference, the current docker build sets the file permissions to 0o644.
Changed the permission check and added a test for allowing 0o644.
Fixes #1007
> fix: relax file permissions

- cmd/proxy/main.go
- config.dev.toml
- pkg/config/config.go
The Athens server currently only supports listening on a TCP port. This change introduces the capability to listen on a Unix domain socket instead, when specified in configuration as `UnixSocket` or in the environment as `ATHENS_UNIX_SOCKET`.
Changes:
* Augment configuration schema to respect `UnixSocket`
* Update main entry point server to create either a TCP or Unix socket listener depending on configuration
* Serve the HTTP server on the initialized listener
```bash
$ ATHENS_UNIX_SOCKET=/tmp/athens.sock ./athens 
2023/04/07 18:15:26 Running dev mode with default settings, consult config when you're ready to run in production
INFO[6:15PM]: Exporter not specified. Traces won't be exported	
2023/04/07 18:15:26 Starting application at Unix domain socket /tmp/athens.sock
```
```bash
$ curl …
```
> Support Unix domain sockets for proxy server listener

- docs/content/configuration/prefill-disk-cache.md
The `pacmod pack` command on the [pre-filling docs](https://docs.gomods.io/configuration/prefill-disk-cache/) was wrong
I fixed it
Ref https://github.com/gomods/athens/issues/1416, because that issue is related to a problem related to using `pacmod` to "side-load" disk storage
> Fixing pacmod command

- cmd/proxy/actions/app_proxy.go
- pkg/config/config_test.go
- pkg/errors/doc.go
- pkg/errors/errors.go
- pkg/log/entry.go
- pkg/log/format.go
- pkg/log/log.go
- pkg/stash/with_redis.go
- pkg/stash/with_redis_test.go
This PR switches all instances of `interface{}` to `any`. The `any` type alias was introduced in Go 1.18 along with generics, and `any` is now conventionally used instead of `interface{}`.
Replace all instances of `interface{}` with `any`.
> chore: switch from `interface{}` to `any`

- cmd/proxy/main.go
- pkg/config/config.go
Athens should not check the permission of TLS files, as it is not compatible with some automatic certificate issuers.
The config method TLSCertFiles has been removed as it was redundant after the change. The return values were never even used.
Fixes #1879
> fix(proxy): don't check TLS file permission

- pkg/stash/with_etcd.go
Athens checks the status of all etcd endpoints when started, which can cause issues when some members of the etcd cluster are unavailable. It is perfectly okay for some members of an etcd cluster to be unavailable, as it's designed for high availability and fault tolerance.
The management of the connections is instead deferred to the etcd client, which will handle failures and load balancing as expected.
Fixes: #1888
> fix(pkg/stash): don't check status of all etcd endpoints on start

- pkg/module/go_get_fetcher.go
- pkg/module/go_vcs_lister.go
see: https://github.com/gomods/athens/pull/1876
Use singleflight package to ensure identical go commands are not run simultaneously.
> singleflight go commands

- cmd/proxy/Dockerfile
Current arm64 docker image contains an arm64 binary (`athens-proxy`) and an amd64 binary (`go`).
I manage to make a build on a private repo and use it on a kubernetes cluster with arm64 nodes.
I used the same kind of command than the one already configured in GH action:
```shell
docker buildx build --build-arg VERSION=v0.13.0 --file cmd/proxy/Dockerfile   --platform linux/amd64,linux/arm64 --tag ${MY_REGISTRY}/athens:v0.13.0-test --push .
```
Fixes #1910 
Follow up of #1862
> fix: arm64 build

- cmd/proxy/main.go
Some packages like [`httputil`'s `ReverseProxy`](https://pkg.go.dev/http/httputil#ReverseProxy) [use the standard `log.Logger`](https://github.com/golang/go/blob/6db1102605f227093ea95538f0fe9e46022ad7ea/src/net/http/httputil/reverseproxy.go#L307) to emit log traces. This means that their output won't match the format of Athens's `logrus` output.
[`logrus.Logger.Writer`](https://pkg.go.dev/github.com/sirupsen/logrus#Logger.Writer)'s documentation states that it "can be used to override the standard library logger easily." It spawns a go routine, so instead of doing that each time we need to make `logrus` look like a (standard) `log.Logger` (and then remembering to `Close()` it right away), this calls `logrus.Writer()` once in `main`, `defer`s the `Close()`,  and sets it into the global …
> Send standard logger's output to logrus

- docs/content/configuration/storage.md
This fixes bad link rendering on https://docs.gomods.io/configuration/storage/:
> Fix Markdown link in Storage docs

- docker-compose.yml
Args in `docker-compose.yaml` were not surrounded by quotes and caste as floats. This worked up until `1.20` where `1.20` was interpreted as `1.2`.
Enclose args in quotes.
N/A
> Use quotes for args

- docs/content/configuration/logging.md
Logging configuration is a bit ambiguous based on reports. `CloudRuntime` affects logging for specific scenarios but many users may want to manually configure the logger.
Adds a page on logging to the docs
N/A
> Add logging configuration docs

- pkg/storage/s3/s3.go
Unable to access s3 with default config in v0.14.0, but v0.13.x works very well.
Fixes https://github.com/gomods/athens/issues/1961
> Fix aws default credentials

- Makefile
- scripts/test_e2e.sh
Fixes issue #1947 where `make test-e2e-docker` fails from calling `scripts/test_e2e.sh`, which does not exist.
created `scripts/test_e2e.sh` which allows us to run the e2e tests in docker compose. I also modified the Makefile to use this script in `make test-e2e` for readability and consistency with `make test-unit`
Fixes #1947
> Fixed "make test-e2e-docker"

- cmd/proxy/actions/app_proxy.go
- config.dev.toml
- docs/content/configuration/storage.md
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/singleflight.go
- pkg/stash/with_gcs.go
- pkg/stash/with_gcs_test.go
- pkg/storage/gcp/gcp.go
- pkg/storage/gcp/saver.go
In #1124, a GCP lock type was added as a singleflight backend. As part of this work, the GCP storage backend's `Save()` was made serial, likely because `moduploader.Upload` requires a call to `Exists()` before it, rendering the GCP lock less useful, by doubling the calls to GCS.
However, by doing this, the existence check was now only checking the existence of the mod file, and not the info or zip. This meant that if during a `Save()`, the zip or info uploads failed, on subsequent rquests, that when using the GCP singleflight backend, Athens woul assume everything had been stashed and saved properly, and then fail to serve up the info or zip that had failed upload, meaning the cache was in an unhealable broklen state, requiring a manual intervention.
To fix this, without breaking the …
> gcp/saver: Only return errors.KindAlreadyExists if all three exist

- cmd/proxy/actions/app.go
- cmd/proxy/actions/catalog.go
- cmd/proxy/actions/health.go
- cmd/proxy/actions/home.go
- cmd/proxy/actions/index.go
- cmd/proxy/actions/readiness.go
- cmd/proxy/actions/robots.go
- cmd/proxy/actions/version.go
- pkg/download/latest.go
- pkg/download/list.go
- pkg/download/version_info.go
- pkg/download/version_module.go
Content types are being sent more than once and are often incorrectly set. See #1930
Set the content type directly on handlers and remove content type middleware
Fixes #1930
Fixes #1958
> Set correct content type and send once

- docs/content/install/install-on-kubernetes.md
Helm install command in the doc was wrong
Update the flags for Name
> Fix helm install command in docs

- .github/workflows/goreleaser.yml
- go.mod
- go.sum
Releases are failing because we [use a deprecated flag](https://goreleaser.com/deprecations/?h=rm+dist#-rm-dist)
N/A
> Fix: Change goreleaser flag from --rm-dist to --clean

- cmd/proxy/actions/app_proxy.go
- pkg/download/list.go
- pkg/download/protocol_test.go
- pkg/errors/errors.go
- pkg/module/go_vcs_lister.go
`vcsLister.List()` can take several minutes to execute for certain modules
Add a `timeout` field to `vcsLister` that can be used when calling `vcsLister.List()`. The timeout is set by `ATHENS_TIMEOUT`
Fixes #1884
> Add timeout to vcsLister.List()

- cmd/proxy/Dockerfile
- pkg/module/prepare_env.go
In v0.15.2, an error occurs when trying to use the proxy:
```
INFO[5:50PM]: exit status 2: go: cannot find GOROOT directory: 'go' binary is trimmed and GOROOT is not set
http-method=GET http-path=/github.com/hamba/avro/@v/list kind=Not Found module= operation=download.ListHandler ops=[download.ListHandler pool.List protocol.List vcsLister.List] request-id=ba64734c-a3b6-4cf2-a0ac-54199c55153a version=
```
It seems in Go 1.21, so defaults are no longer baked into the binary, causing issues when running Go.
My first attempt at a fix was to set `GOROOT` in the Dockerfile, but Athens does not pass all env vars to the Go binary when executing it. I did consider passing `GOROOT` by default to the Go binary, but this seems wrong for people not running the docker image. There are also multiple go …
> fix: go in docker failing

- cmd/proxy/Dockerfile
#1988 had a type in the URL which prevented `git-credential-github-app` being installed properly (v0.2.0 in the filename but v0.3.0 in the path)
Found the correct URL from the releases page and copied it in
N/A
> Fix typo preventing git-credential-github-app being installed

- README.md
The README Slack link points to the Gophers Slack but is not an invite link
Generated a Slack invite link on Gophers that doesn't expire
Fixes #2013
> Fix the README Slack link

- .github/workflows/ci.yml
- cmd/proxy/actions/app_proxy.go
- config.dev.toml
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/config/singleflight.go
- pkg/stash/with_redis_sentinel.go
- pkg/stash/with_redis_sentinel_test.go
Introduced Redis master authentication parameters (username and password) to the Redis Sentinel setup. This enhances compatibility with Redis environments that require authentication for both sentinel and master nodes.
There is no way to provide master node authentication credentials when using Single Flight mode with Redis Sentinel. 
The only parameter that can be used is `SentinelPassword`, but in my scenario, I have Redis Sentinel with password authentication and Redis Master Node with password authentication as well. As a result, I receive an error: `NOAUTH Authentication required`.
```
INFO[10:05AM]: Exporter not specified. Traces won't be exported
INFO[10:05M]: sentinel: discovered new sentinel="XX.XX.XX.XX:26379" for master="athens"
INFO[10:05AM]: sentinel: new master="athens" …
```
> Redis Sentinel SingeFlight: support of Redis master node username and password

- cmd/proxy/main.go
- internal/shutdown/signals.go
- internal/shutdown/signals_notunix.go
Athens is constantly spawning child processes to run the go toolchain for module management and downloading. The go toolchain also spawns child processes for git, which spawns child processes to use ssh, when appropriate.
Occasionally, things go wrong with these child processes, which can then end up as zombie processes. Currently, these zombies are not being reaped, causing significant resource leakage over extended times. This is especially problematic in shared resource environments, like Kubernetes.
This change adds handling for the `SIGCHLD` signal, waiting on the child processes to cleanup their resources. It also updates the shutdown signal handling to make use of NotifyContext.
None
> Add handling for SIGCHLD to cleanup child processes

- pkg/errors/command.go
- pkg/module/go_get_fetcher.go
- pkg/module/go_vcs_lister.go
Package download sometimes fails with error `waitid: no child processes`, due to a race condition described in the code snippet below:
https://github.com/slimtoolkit/slim/blob/79b63a80c10083ece51be0ef1fd1e7c090ff6346/pkg/util/errutil/errutil.go#L95-L110
A GitHub search (e.g. <https://github.com/search?q=%22waitid%3A+no+child+processes%22&type=code>) also shows a similar workaround in many other Go projects.
For `exec.Command().Run()`, ignore the error (set the error to `nil`) if the error corresponds to the issue above.
(No GitHub issue yet)
> Fix no child processes error

- pkg/module/go_get_fetcher.go
- pkg/stash/stasher.go
This issue addresses some cache corruption issue within Athens when there are multiple requests in-flight to a package that is not yet cached.
When multiple requests are sent to the same package, each request calls `stasher.Stash`, and each call `fetcher.Fetch`.
The implementation of `goGetFetcher.Fetch` uses [singleflight.Group](https://pkg.go.dev/golang.org/x/sync/singleflight#Group) to prevent fetching the same package multiple times. As such, it returns a shared `storage.Version` for each `stasher.Stash`, which goes on to call `storage.Save`.
The problem here, is that the `Zip io.ReadCloser` within `storage.Version` is shared between the 2 calls to `storage.Save`. When the storage implementation tries to use the `io.ReadCloser` through e.g. `io.Copy`, the buffer is being consumed by …
> Move Single-flight from Fetcher to Stasher

- cmd/proxy/actions/home.go
- docs/content/configuration/home-template.md
The home page was introduced in #1945 or commit 359c119441ec75baea05161932d66cc20822bae0. This commit fixes a typo; the correct Go environment variable is `GONOSUMDB` instead of `GONOSUM`.
When looking at the home page of Athens, it instructs the user to use `GONOSUM`, which isn't a recognized [Go environment variable](https://pkg.go.dev/cmd/go#hdr-Environment_variables). `GONOSUMDB` is the correct environment variable.
The built-in home page is automatically updated when building `cmd/proxy`. If a user customized this template (see `docs/content/configuration/home-template.md`), they may need to manually update their template if it contained `GONOSUM` instead of `GONOSUMDB`.
None
> docfix: use `GONOSUMDB` on Athens' home page

- pkg/download/list_merge_test.go
- pkg/download/protocol_test.go
- pkg/module/go_get_fetcher.go
- pkg/stash/stasher.go
- pkg/stash/stasher_test.go
- pkg/stash/with_azureblob_test.go
- pkg/stash/with_gcs_test.go
- pkg/stash/with_redis_test.go
- pkg/storage/azureblob/saver.go
- pkg/storage/compliance/benchmarks.go
- pkg/storage/compliance/tests.go
- pkg/storage/external/client.go
- pkg/storage/external/server.go
- pkg/storage/fs/saver.go
- pkg/storage/gcp/saver.go
- pkg/storage/minio/saver.go
- pkg/storage/mongo/mongo_test.go
- pkg/storage/mongo/saver.go
- pkg/storage/s3/saver.go
- pkg/storage/saver.go
- pkg/storage/version.go
Continuing the GCP storage backend lock removal, this PR aims to prevent regressions in future changes by precomputing the MD5 checksum and passing the checksum when uploading the file.
The computed checksum can be used for any storage provider; however, it is currently only implemented for GCP backend.
* Further protect against corrupt cache by precomputing the MD5 sum for the ZIP file.
* Modify the `Saver` interface to accept the MD5 sum, and clarify the contract between the Saver implementation and the Saver user regarding the MD5 sum.
* Implement checksum in upload for **GCP** backend only.
* Other backends have checksum passed to the implementation, but we did not implement passing the checksum to the upload to prevent breaking existing users since we have no way to test those …
> Add Checksum to Saver (+ GCP implementation)

- .github/dependabot.yml
resolve and prevent issues like #2055 that may be caused from outdated docker base image.
Enable dependabot for the Dockerfile to keep the base image up to date.
May fix #2055, a scan with `trivy` does not show vulnerabilities from alpine base image 3.22.
> fix: enable dependabot for Dockerfile

- .github/dependabot.yml
- cmd/proxy/Dockerfile
Dependabot does not detect docker image version/tag, if we use a variable.
Explicitly set the tag/version of the Alpine image, then Dependabot detects it and creates PRs.
Tested with dependabot locally: `dependabot update docker drpsychick/athens --local ./ -d /cmd/proxy`
Fixes #2055 (previous attempt #2060)
> fix: explicit alpine version, so dependabot detects it

- .github/workflows/ci.yml
- Makefile
- cmd/proxy/Dockerfile
- docker-compose.yml
- scripts/build-image/Dockerfile
Resolve issues with athens not being able to fetch modules with toolchain >= 1.25
Update image go version to 1.25.1
Fixes #2054
> chore: update container image to go 1.25.1
